import 'package:access_to_dart/src/analysis_model.dart';
import 'package:access_to_dart/src/migration_auto_number_mode.dart';
import 'package:access_to_dart/src/migration_identifier_style.dart';
import 'package:access_to_dart/src/migration_not_null_mode.dart';
import 'package:access_to_dart/src/migration_statement_builder.dart';
import 'package:test/test.dart';

void main() {
  test('preserva defaults semanticos do Access no schema PostgreSQL', () {
    final project = AnalysisProject(
      schemaVersion: '1.0',
      source: 'fixtures/demo.accdb',
      format: 'VERSION_16',
      summary: const <String, dynamic>{},
      tables: [
        AnalysisTable(
          name: 'Clientes',
          rowCount: 0,
          postgresDdl: null,
          dartClassName: null,
          columns: [
            AnalysisColumn(
              name: 'IdExterno',
              typeName: 'GUID',
              typeCode: 0,
              isAutoNumber: false,
              isCalculated: false,
              isRequired: true,
              caption: null,
              defaultValue: 'GenGUID()',
              maxLength: null,
              calculatedExpression: null,
              validationRule: null,
              validationText: null,
              description: null,
              decimalPlaces: null,
              displayControl: null,
              textFormat: null,
              imeMode: null,
              imeSentenceMode: null,
              resultType: null,
              propertyGuid: null,
              allowMultipleValues: null,
              rowSourceType: null,
              rowSource: null,
              wssFieldId: null,
              formatString: null,
              inputMask: null,
              allowZeroLength: null,
              precision: null,
              scale: null,
            ),
            AnalysisColumn(
              name: 'Status',
              typeName: 'Text',
              typeCode: 0,
              isAutoNumber: false,
              isCalculated: false,
              isRequired: false,
              caption: null,
              defaultValue: 'NEW',
              maxLength: null,
              calculatedExpression: null,
              validationRule: null,
              validationText: null,
              description: null,
              decimalPlaces: null,
              displayControl: null,
              textFormat: null,
              imeMode: null,
              imeSentenceMode: null,
              resultType: null,
              propertyGuid: null,
              allowMultipleValues: null,
              rowSourceType: null,
              rowSource: null,
              wssFieldId: null,
              formatString: null,
              inputMask: null,
              allowZeroLength: null,
              precision: null,
              scale: null,
            ),
            AnalysisColumn(
              name: 'CriadoEm',
              typeName: 'DateTime',
              typeCode: 0,
              isAutoNumber: false,
              isCalculated: false,
              isRequired: false,
              caption: null,
              defaultValue: '#1/1/1900#',
              maxLength: null,
              calculatedExpression: null,
              validationRule: null,
              validationText: null,
              description: null,
              decimalPlaces: null,
              displayControl: null,
              textFormat: null,
              imeMode: null,
              imeSentenceMode: null,
              resultType: null,
              propertyGuid: null,
              allowMultipleValues: null,
              rowSourceType: null,
              rowSource: null,
              wssFieldId: null,
              formatString: null,
              inputMask: null,
              allowZeroLength: null,
              precision: null,
              scale: null,
            ),
            AnalysisColumn(
              name: 'Codigo',
              typeName: 'Long',
              typeCode: 0,
              isAutoNumber: false,
              isCalculated: false,
              isRequired: false,
              caption: null,
              defaultValue: 'Int(13.9)',
              maxLength: null,
              calculatedExpression: null,
              validationRule: null,
              validationText: null,
              description: null,
              decimalPlaces: null,
              displayControl: null,
              textFormat: null,
              imeMode: null,
              imeSentenceMode: null,
              resultType: null,
              propertyGuid: null,
              allowMultipleValues: null,
              rowSourceType: null,
              rowSource: null,
              wssFieldId: null,
              formatString: null,
              inputMask: null,
              allowZeroLength: null,
              precision: null,
              scale: null,
            ),
            AnalysisColumn(
              name: 'DataAgenda',
              typeName: 'DateTime',
              typeCode: 0,
              isAutoNumber: false,
              isCalculated: false,
              isRequired: false,
              caption: null,
              defaultValue: 'DateSerial(2024, 2, 30)',
              maxLength: null,
              calculatedExpression: null,
              validationRule: null,
              validationText: null,
              description: null,
              decimalPlaces: null,
              displayControl: null,
              textFormat: null,
              imeMode: null,
              imeSentenceMode: null,
              resultType: null,
              propertyGuid: null,
              allowMultipleValues: null,
              rowSourceType: null,
              rowSource: null,
              wssFieldId: null,
              formatString: null,
              inputMask: null,
              allowZeroLength: null,
              precision: null,
              scale: null,
            ),
            AnalysisColumn(
              name: 'HorarioBase',
              typeName: 'DateTime',
              typeCode: 0,
              isAutoNumber: false,
              isCalculated: false,
              isRequired: false,
              caption: null,
              defaultValue: 'TimeSerial(15, 57, 34)',
              maxLength: null,
              calculatedExpression: null,
              validationRule: null,
              validationText: null,
              description: null,
              decimalPlaces: null,
              displayControl: null,
              textFormat: null,
              imeMode: null,
              imeSentenceMode: null,
              resultType: null,
              propertyGuid: null,
              allowMultipleValues: null,
              rowSourceType: null,
              rowSource: null,
              wssFieldId: null,
              formatString: null,
              inputMask: null,
              allowZeroLength: null,
              precision: null,
              scale: null,
            ),
            AnalysisColumn(
              name: 'StatusNormalizado',
              typeName: 'Text',
              typeCode: 0,
              isAutoNumber: false,
              isCalculated: false,
              isRequired: false,
              caption: null,
              defaultValue: 'Trim("  ativo  ")',
              maxLength: null,
              calculatedExpression: null,
              validationRule: null,
              validationText: null,
              description: null,
              decimalPlaces: null,
              displayControl: null,
              textFormat: null,
              imeMode: null,
              imeSentenceMode: null,
              resultType: null,
              propertyGuid: null,
              allowMultipleValues: null,
              rowSourceType: null,
              rowSource: null,
              wssFieldId: null,
              formatString: null,
              inputMask: null,
              allowZeroLength: null,
              precision: null,
              scale: null,
            ),
          ],
          indexes: const [],
          sampleRows: const [],
        ),
      ],
      linkedTables: const [],
      relationships: const [],
      forms: const [],
      canonicalAnalysis: null,
      queryReconciliation: null,
      raw: const <String, dynamic>{},
    );

    const builder = MigrationStatementBuilder(
      identifierPolicy: MigrationIdentifierPolicy(
        style: MigrationIdentifierStyle.snakeAscii,
      ),
      notNullMode: MigrationNotNullMode.strict,
    );

    final schema = builder.buildSchema(project);

    expect(schema, contains('CREATE EXTENSION IF NOT EXISTS pgcrypto;'));
    expect(schema, contains('"id_externo" UUID NOT NULL DEFAULT gen_random_uuid()'));
    expect(schema, contains('"status" TEXT DEFAULT \'NEW\''));
    expect(schema, contains('"criado_em" TIMESTAMP DEFAULT \'1/1/1900\''));
    expect(schema, contains('"codigo" INTEGER DEFAULT FLOOR(13.9)'));
    expect(schema, contains('"data_agenda" TIMESTAMP DEFAULT ((MAKE_DATE(CASE WHEN (2024) BETWEEN 0 AND 29 THEN 2000 + (2024) WHEN (2024) BETWEEN 30 AND 99 THEN 1900 + (2024) ELSE (2024) END, 1, 1) + ((2) - 1) * INTERVAL \'1 month\' + ((30) - 1) * INTERVAL \'1 day\'))::timestamp'));
    expect(schema, contains('"horario_base" TIMESTAMP DEFAULT (TIMESTAMP \'1899-12-30 00:00:00\' + (15) * INTERVAL \'1 hour\' + (57) * INTERVAL \'1 minute\' + (34) * INTERVAL \'1 second\')'));
    expect(schema, contains('"status_normalizado" TEXT DEFAULT BTRIM(\'  ativo  \')'));
  });

  test('adianta sequences antes do seed quando ha autonumber explicito', () {
    final project = AnalysisProject(
      schemaVersion: '1.0',
      source: 'fixtures/demo.accdb',
      format: 'VERSION_16',
      summary: const <String, dynamic>{},
      tables: [
        AnalysisTable(
          name: 'Pedidos',
          rowCount: 3,
          postgresDdl: null,
          dartClassName: null,
          columns: [
            AnalysisColumn(
              name: 'CodPedido',
              typeName: 'Long',
              typeCode: 0,
              isAutoNumber: true,
              isCalculated: false,
              isRequired: true,
              caption: null,
              defaultValue: null,
              maxLength: null,
              calculatedExpression: null,
              validationRule: null,
              validationText: null,
              description: null,
              decimalPlaces: null,
              displayControl: null,
              textFormat: null,
              imeMode: null,
              imeSentenceMode: null,
              resultType: null,
              propertyGuid: null,
              allowMultipleValues: null,
              rowSourceType: null,
              rowSource: null,
              wssFieldId: null,
              formatString: null,
              inputMask: null,
              allowZeroLength: null,
              precision: null,
              scale: null,
            ),
            AnalysisColumn(
              name: 'Nome',
              typeName: 'Text',
              typeCode: 0,
              isAutoNumber: false,
              isCalculated: false,
              isRequired: false,
              caption: null,
              defaultValue: null,
              maxLength: null,
              calculatedExpression: null,
              validationRule: null,
              validationText: null,
              description: null,
              decimalPlaces: null,
              displayControl: null,
              textFormat: null,
              imeMode: null,
              imeSentenceMode: null,
              resultType: null,
              propertyGuid: null,
              allowMultipleValues: null,
              rowSourceType: null,
              rowSource: null,
              wssFieldId: null,
              formatString: null,
              inputMask: null,
              allowZeroLength: null,
              precision: null,
              scale: null,
            ),
          ],
          indexes: [
            AnalysisIndex(
              name: 'PrimaryKey',
              indexNumber: 0,
              backingDataNumber: 0,
              isPrimaryKey: true,
              isForeignKey: false,
              isUnique: true,
              isRequired: true,
              ignoreNulls: false,
              flags: null,
              columns: [
                AnalysisIndexColumn(
                  name: 'CodPedido',
                  columnNumber: 0,
                  ascending: true,
                  flags: null,
                ),
              ],
            ),
          ],
          sampleRows: const [],
        ),
      ],
      linkedTables: const [],
      relationships: const [],
      forms: const [],
      canonicalAnalysis: null,
      queryReconciliation: null,
      raw: const <String, dynamic>{},
    );

    const builder = MigrationStatementBuilder(
      identifierPolicy: MigrationIdentifierPolicy(
        style: MigrationIdentifierStyle.snakeAscii,
      ),
      autoNumberMode: MigrationAutoNumberMode.sequence,
    );

    final statements = builder.buildPreInsertStatements(
      project,
      tableRowsByName: const {
        'Pedidos': [
          {'CodPedido': 7, 'Nome': 'A'},
          {'Nome': 'B'},
          {'CodPedido': 11, 'Nome': 'C'},
        ],
      },
    );

    expect(
      statements,
      contains(
        'SELECT setval(\'"pedidos_cod_pedido_seq"\'::regclass, 11, true);',
      ),
    );
  });

  test('omite autonumber invalido para deixar a sequence assumir', () {
    final table = AnalysisTable(
      name: 'Pedidos',
      rowCount: 0,
      postgresDdl: null,
      dartClassName: null,
      columns: [
        AnalysisColumn(
          name: 'CodPedido',
          typeName: 'Long',
          typeCode: 0,
          isAutoNumber: true,
          isCalculated: false,
          isRequired: true,
          caption: null,
          defaultValue: null,
          maxLength: null,
          calculatedExpression: null,
          validationRule: null,
          validationText: null,
          description: null,
          decimalPlaces: null,
          displayControl: null,
          textFormat: null,
          imeMode: null,
          imeSentenceMode: null,
          resultType: null,
          propertyGuid: null,
          allowMultipleValues: null,
          rowSourceType: null,
          rowSource: null,
          wssFieldId: null,
          formatString: null,
          inputMask: null,
          allowZeroLength: null,
          precision: null,
          scale: null,
        ),
        AnalysisColumn(
          name: 'Nome',
          typeName: 'Text',
          typeCode: 0,
          isAutoNumber: false,
          isCalculated: false,
          isRequired: false,
          caption: null,
          defaultValue: null,
          maxLength: null,
          calculatedExpression: null,
          validationRule: null,
          validationText: null,
          description: null,
          decimalPlaces: null,
          displayControl: null,
          textFormat: null,
          imeMode: null,
          imeSentenceMode: null,
          resultType: null,
          propertyGuid: null,
          allowMultipleValues: null,
          rowSourceType: null,
          rowSource: null,
          wssFieldId: null,
          formatString: null,
          inputMask: null,
          allowZeroLength: null,
          precision: null,
          scale: null,
        ),
      ],
      indexes: const [],
      sampleRows: const [],
    );

    const builder = MigrationStatementBuilder(
      identifierPolicy: MigrationIdentifierPolicy(
        style: MigrationIdentifierStyle.snakeAscii,
      ),
      autoNumberMode: MigrationAutoNumberMode.sequence,
    );

    final statements = builder.buildInsertStatements(table, const [
      {'CodPedido': 0, 'Nome': 'A'},
    ]).toList();

    expect(
      statements.single,
      'INSERT INTO "pedidos" ("nome") VALUES (\'A\');',
    );
  });

  test('plain-int nao cria sequence para autonumber', () {
    final table = AnalysisTable(
      name: 'Pedidos',
      rowCount: 0,
      postgresDdl: null,
      dartClassName: null,
      columns: [
        AnalysisColumn(
          name: 'CodPedido',
          typeName: 'Long',
          typeCode: 0,
          isAutoNumber: true,
          isCalculated: false,
          isRequired: true,
          caption: null,
          defaultValue: null,
          maxLength: null,
          calculatedExpression: null,
          validationRule: null,
          validationText: null,
          description: null,
          decimalPlaces: null,
          displayControl: null,
          textFormat: null,
          imeMode: null,
          imeSentenceMode: null,
          resultType: null,
          propertyGuid: null,
          allowMultipleValues: null,
          rowSourceType: null,
          rowSource: null,
          wssFieldId: null,
          formatString: null,
          inputMask: null,
          allowZeroLength: null,
          precision: null,
          scale: null,
        ),
      ],
      indexes: const [],
      sampleRows: const [],
    );
    final project = AnalysisProject(
      schemaVersion: '1.0',
      source: 'fixtures/demo.accdb',
      format: 'VERSION_16',
      summary: const <String, dynamic>{},
      tables: [table],
      linkedTables: const [],
      relationships: const [],
      forms: const [],
      canonicalAnalysis: null,
      queryReconciliation: null,
      raw: const <String, dynamic>{},
    );

    const builder = MigrationStatementBuilder(
      identifierPolicy: MigrationIdentifierPolicy(
        style: MigrationIdentifierStyle.snakeAscii,
      ),
      autoNumberMode: MigrationAutoNumberMode.plainInt,
      notNullMode: MigrationNotNullMode.strict,
    );

    final schema = builder.buildSchema(project);

    expect(schema, isNot(contains('CREATE SEQUENCE')));
    expect(schema, contains('"cod_pedido" INTEGER NOT NULL'));
    expect(schema, isNot(contains('nextval(')));
  });

  test('force-sequence omite autonumber explicito mesmo quando positivo', () {
    final table = AnalysisTable(
      name: 'Pedidos',
      rowCount: 0,
      postgresDdl: null,
      dartClassName: null,
      columns: [
        AnalysisColumn(
          name: 'CodPedido',
          typeName: 'Long',
          typeCode: 0,
          isAutoNumber: true,
          isCalculated: false,
          isRequired: true,
          caption: null,
          defaultValue: null,
          maxLength: null,
          calculatedExpression: null,
          validationRule: null,
          validationText: null,
          description: null,
          decimalPlaces: null,
          displayControl: null,
          textFormat: null,
          imeMode: null,
          imeSentenceMode: null,
          resultType: null,
          propertyGuid: null,
          allowMultipleValues: null,
          rowSourceType: null,
          rowSource: null,
          wssFieldId: null,
          formatString: null,
          inputMask: null,
          allowZeroLength: null,
          precision: null,
          scale: null,
        ),
        AnalysisColumn(
          name: 'Nome',
          typeName: 'Text',
          typeCode: 0,
          isAutoNumber: false,
          isCalculated: false,
          isRequired: false,
          caption: null,
          defaultValue: null,
          maxLength: null,
          calculatedExpression: null,
          validationRule: null,
          validationText: null,
          description: null,
          decimalPlaces: null,
          displayControl: null,
          textFormat: null,
          imeMode: null,
          imeSentenceMode: null,
          resultType: null,
          propertyGuid: null,
          allowMultipleValues: null,
          rowSourceType: null,
          rowSource: null,
          wssFieldId: null,
          formatString: null,
          inputMask: null,
          allowZeroLength: null,
          precision: null,
          scale: null,
        ),
      ],
      indexes: const [],
      sampleRows: const [],
    );

    const builder = MigrationStatementBuilder(
      identifierPolicy: MigrationIdentifierPolicy(
        style: MigrationIdentifierStyle.snakeAscii,
      ),
      autoNumberMode: MigrationAutoNumberMode.forceSequence,
    );

    final statements = builder.buildInsertStatements(table, const [
      {'CodPedido': 42, 'Nome': 'A'},
    ]).toList();

    expect(
      statements.single,
      'INSERT INTO "pedidos" ("nome") VALUES (\'A\');',
    );
  });

  test('skip-row descarta linha com required nulo', () {
    final table = AnalysisTable(
      name: 'Pessoas',
      rowCount: 0,
      postgresDdl: null,
      dartClassName: null,
      columns: [
        AnalysisColumn(
          name: 'Nome',
          typeName: 'Text',
          typeCode: 0,
          isAutoNumber: false,
          isCalculated: false,
          isRequired: true,
          caption: null,
          defaultValue: null,
          maxLength: null,
          calculatedExpression: null,
          validationRule: null,
          validationText: null,
          description: null,
          decimalPlaces: null,
          displayControl: null,
          textFormat: null,
          imeMode: null,
          imeSentenceMode: null,
          resultType: null,
          propertyGuid: null,
          allowMultipleValues: null,
          rowSourceType: null,
          rowSource: null,
          wssFieldId: null,
          formatString: null,
          inputMask: null,
          allowZeroLength: null,
          precision: null,
          scale: null,
        ),
      ],
      indexes: const [],
      sampleRows: const [],
    );

    const builder = MigrationStatementBuilder(
      identifierPolicy: MigrationIdentifierPolicy(
        style: MigrationIdentifierStyle.snakeAscii,
      ),
      notNullMode: MigrationNotNullMode.skipRow,
    );

    final statements = builder.buildInsertStatements(table, const [
      {'Nome': ''},
    ]).toList();

    expect(statements, isEmpty);
  });

  test('relax-not-null remove NOT NULL de coluna requerida nao PK', () {
    final table = AnalysisTable(
      name: 'Pessoas',
      rowCount: 0,
      postgresDdl: null,
      dartClassName: null,
      columns: [
        AnalysisColumn(
          name: 'Nome',
          typeName: 'Text',
          typeCode: 0,
          isAutoNumber: false,
          isCalculated: false,
          isRequired: true,
          caption: null,
          defaultValue: null,
          maxLength: null,
          calculatedExpression: null,
          validationRule: null,
          validationText: null,
          description: null,
          decimalPlaces: null,
          displayControl: null,
          textFormat: null,
          imeMode: null,
          imeSentenceMode: null,
          resultType: null,
          propertyGuid: null,
          allowMultipleValues: null,
          rowSourceType: null,
          rowSource: null,
          wssFieldId: null,
          formatString: null,
          inputMask: null,
          allowZeroLength: null,
          precision: null,
          scale: null,
        ),
      ],
      indexes: const [],
      sampleRows: const [],
    );

    const builder = MigrationStatementBuilder(
      identifierPolicy: MigrationIdentifierPolicy(
        style: MigrationIdentifierStyle.snakeAscii,
      ),
      notNullMode: MigrationNotNullMode.relaxNotNull,
    );

    final sql = builder.buildCreateTableStatement(table);

    expect(sql, contains('"nome" TEXT'));
    expect(sql, isNot(contains('"nome" TEXT NOT NULL')));
  });

  test('fix preenche required nulo com valor sintetico', () {
    final table = AnalysisTable(
      name: 'Pessoas',
      rowCount: 0,
      postgresDdl: null,
      dartClassName: null,
      columns: [
        AnalysisColumn(
          name: 'Nome',
          typeName: 'Text',
          typeCode: 0,
          isAutoNumber: false,
          isCalculated: false,
          isRequired: true,
          caption: null,
          defaultValue: null,
          maxLength: null,
          calculatedExpression: null,
          validationRule: null,
          validationText: null,
          description: null,
          decimalPlaces: null,
          displayControl: null,
          textFormat: null,
          imeMode: null,
          imeSentenceMode: null,
          resultType: null,
          propertyGuid: null,
          allowMultipleValues: null,
          rowSourceType: null,
          rowSource: null,
          wssFieldId: null,
          formatString: null,
          inputMask: null,
          allowZeroLength: null,
          precision: null,
          scale: null,
        ),
        AnalysisColumn(
          name: 'Idade',
          typeName: 'Long',
          typeCode: 0,
          isAutoNumber: false,
          isCalculated: false,
          isRequired: true,
          caption: null,
          defaultValue: null,
          maxLength: null,
          calculatedExpression: null,
          validationRule: null,
          validationText: null,
          description: null,
          decimalPlaces: null,
          displayControl: null,
          textFormat: null,
          imeMode: null,
          imeSentenceMode: null,
          resultType: null,
          propertyGuid: null,
          allowMultipleValues: null,
          rowSourceType: null,
          rowSource: null,
          wssFieldId: null,
          formatString: null,
          inputMask: null,
          allowZeroLength: null,
          precision: null,
          scale: null,
        ),
      ],
      indexes: const [],
      sampleRows: const [],
    );

    const builder = MigrationStatementBuilder(
      identifierPolicy: MigrationIdentifierPolicy(
        style: MigrationIdentifierStyle.snakeAscii,
      ),
      notNullMode: MigrationNotNullMode.fix,
    );

    final statements = builder.buildInsertStatements(table, const [
      {'Nome': '', 'Idade': null},
    ]).toList();

    expect(
      statements.single,
      'INSERT INTO "pessoas" ("nome", "idade") VALUES (\'\', -1);',
    );
  });
}
