name: jackcess_dart
description: Pure-Dart foundation for reading Microsoft Access databases.
version: 1.0.0
repository: https://github.com/insinfo/access_to_dart.git

environment:
  sdk: ^3.6.2


dependencies:
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
