import 'dart:convert';
import 'dart:io';

import 'analysis_model.dart';
import 'migration_auto_number_mode.dart';
import 'migration_export_mode.dart';
import 'migration_identifier_style.dart';
import 'migration_not_null_mode.dart';
import 'migration_seed_format.dart';
import 'migration_statement_builder.dart';
import 'migration_unique_mode.dart';

class MigrationArtifacts {
  final File schemaFile;
  final File seedFile;
  final File manifestFile;

  MigrationArtifacts({
    required this.schemaFile,
    required this.seedFile,
    required this.manifestFile,
  });
}

class MigrationWriter {
  Future<MigrationArtifacts> write({
    required AnalysisProject project,
    required String outputDirectory,
    String? connectionString,
    MigrationIdentifierStyle identifierStyle =
        MigrationIdentifierStyle.snakeAscii,
    MigrationAutoNumberMode autoNumberMode =
        MigrationAutoNumberMode.plainInt,
    MigrationNotNullMode notNullMode = MigrationNotNullMode.relaxNotNull,
    MigrationUniqueMode uniqueMode = MigrationUniqueMode.relaxUnique,
    MigrationSeedFormat seedFormat = MigrationSeedFormat.insert,
    MigrationExportMode exportMode = MigrationExportMode.schemaAndData,
    Map<String, List<Map<String, dynamic>>>? tableRowsByName,
  }) async {
    final directory = Directory(outputDirectory);
    await directory.create(recursive: true);

    final statementBuilder = MigrationStatementBuilder(
      identifierPolicy: MigrationIdentifierPolicy(style: identifierStyle),
      autoNumberMode: autoNumberMode,
      notNullMode: notNullMode,
      uniqueMode: uniqueMode,
    );

    final schemaFile = File(
      '${directory.path}${Platform.pathSeparator}schema.sql',
    );
    final seedFile = File(
      '${directory.path}${Platform.pathSeparator}seed.sql',
    );
    final manifestFile = File(
      '${directory.path}${Platform.pathSeparator}migration_manifest.json',
    );

    await schemaFile.writeAsString(
      statementBuilder.buildSchema(
        project,
        exportMode: exportMode,
        tableRowsByName: tableRowsByName,
      ),
    );
    await seedFile.writeAsString(
      exportMode.includesData
          ? statementBuilder.buildSeed(
              project,
              seedFormat: seedFormat,
              tableRowsByName: tableRowsByName,
            )
          : '-- Generated by access_to_dart\n-- Seed skipped: schema-only export mode\n',
    );
    await manifestFile.writeAsString(
      const JsonEncoder.withIndent('  ').convert({
        'source': project.source,
        'format': project.format,
        'tableCount': project.tables.length,
        'linkedTableCount': project.linkedTables.length,
        'generatedAtUtc': DateTime.now().toUtc().toIso8601String(),
        'identifierStyle': identifierStyle.cliValue,
        'autoNumberMode': autoNumberMode.cliValue,
        'notNullMode': notNullMode.cliValue,
        'uniqueMode': uniqueMode.cliValue,
        'seedFormat': seedFormat.cliValue,
        'exportMode': exportMode.cliValue,
        'fullDataIncluded': exportMode.includesData && tableRowsByName != null,
        'rowCount': exportMode.includesData
            ? (tableRowsByName?.values ?? const <List<Map<String, dynamic>>>[])
                .fold<int>(0, (sum, rows) => sum + rows.length)
            : 0,
        'targetConnectionProvided':
            connectionString != null && connectionString.isNotEmpty,
      }),
    );

    return MigrationArtifacts(
      schemaFile: schemaFile,
      seedFile: seedFile,
      manifestFile: manifestFile,
    );
  }
}
