import 'dart:convert';
import 'dart:io';

import 'analysis_model.dart';
import 'identifier_utils.dart';

class MigrationArtifacts {
  final File schemaFile;
  final File seedFile;
  final File manifestFile;

  MigrationArtifacts({
    required this.schemaFile,
    required this.seedFile,
    required this.manifestFile,
  });
}

class MigrationWriter {
  Future<MigrationArtifacts> write({
    required AnalysisProject project,
    required String outputDirectory,
    String? connectionString,
  }) async {
    final directory = Directory(outputDirectory);
    await directory.create(recursive: true);

    final schemaFile = File(
      '${directory.path}${Platform.pathSeparator}schema.sql',
    );
    final seedFile = File(
      '${directory.path}${Platform.pathSeparator}seed.sql',
    );
    final manifestFile = File(
      '${directory.path}${Platform.pathSeparator}migration_manifest.json',
    );

    await schemaFile.writeAsString(_buildSchema(project));
    await seedFile.writeAsString(_buildSeed(project));
    await manifestFile.writeAsString(
      const JsonEncoder.withIndent('  ').convert({
        'source': project.source,
        'format': project.format,
        'tableCount': project.tables.length,
        'linkedTableCount': project.linkedTables.length,
        'generatedAtUtc': DateTime.now().toUtc().toIso8601String(),
        'targetConnectionProvided':
            connectionString != null && connectionString.isNotEmpty,
      }),
    );

    return MigrationArtifacts(
      schemaFile: schemaFile,
      seedFile: seedFile,
      manifestFile: manifestFile,
    );
  }

  String _buildSchema(AnalysisProject project) {
    final buffer = StringBuffer();
    buffer.writeln('-- Generated by access_to_dart');
    buffer.writeln('-- Source: ${project.source}');
    buffer.writeln();
    for (final table in project.tables) {
      final ddl = table.postgresDdl;
      if (ddl != null && ddl.trim().isNotEmpty) {
        buffer.writeln(ddl.trimRight());
      } else {
        buffer.writeln(_fallbackCreateTable(table));
      }
      buffer.writeln();
    }
    return buffer.toString();
  }

  String _buildSeed(AnalysisProject project) {
    final buffer = StringBuffer();
    buffer.writeln('-- Generated by access_to_dart');
    buffer.writeln('-- Sample rows extracted from analysis.json');
    buffer.writeln();
    for (final table in project.tables) {
      final rows = table.sampleRows;
      if (rows.isEmpty) continue;
      final tableName = toSnakeCaseIdentifier(table.name);
      for (final row in rows) {
        final columnNames = <String>[];
        final values = <String>[];
        row.forEach((key, value) {
          columnNames.add('"${toSnakeCaseIdentifier(key)}"');
          values.add(_sqlLiteral(value));
        });
        buffer.writeln(
          'INSERT INTO "$tableName" (${columnNames.join(', ')}) VALUES (${values.join(', ')});',
        );
      }
      buffer.writeln();
    }
    return buffer.toString();
  }

  String _fallbackCreateTable(AnalysisTable table) {
    final lines = <String>[];
    for (final column in table.columns) {
      lines.add(
        '  "${toSnakeCaseIdentifier(column.name)}" ${_postgresType(column)}',
      );
    }
    return 'CREATE TABLE "${toSnakeCaseIdentifier(table.name)}" (\n${lines.join(',\n')}\n);';
  }

  String _postgresType(AnalysisColumn column) {
    final normalized = foldToAscii(column.typeName).toLowerCase();
    switch (normalized) {
      case 'byte':
      case 'int':
      case 'integer':
      case 'long':
      case 'complextype':
        return 'INTEGER';
      case 'double':
      case 'float':
        return 'DOUBLE PRECISION';
      case 'numeric':
        return _numericType(column);
      case 'money':
      case 'currency':
        return 'NUMERIC(19,4)';
      case 'datetime':
        return 'TIMESTAMP';
      case 'yesno':
      case 'boolean':
        return 'BOOLEAN';
      case 'memo':
      case 'longtext':
        return 'TEXT';
      default:
        return 'TEXT';
    }
  }

  String _numericType(AnalysisColumn column) {
    final precision = column.precision;
    final scale = column.scale;
    if (precision != null && scale != null && precision > 0 && scale >= 0) {
      return 'NUMERIC($precision,$scale)';
    }
    if (precision != null && precision > 0) {
      return 'NUMERIC($precision)';
    }
    return 'NUMERIC';
  }

  String _sqlLiteral(Object? value) {
    if (value == null) return 'NULL';
    if (value is num || value is bool) return '$value';
    final text = value.toString().replaceAll("'", "''");
    return "'$text'";
  }
}
