import 'dart:typed_data';

import 'analysis_model.dart';
import 'identifier_utils.dart';
import 'migration_identifier_style.dart';

class MigrationStatementBuilder {
  final MigrationIdentifierPolicy identifierPolicy;

  const MigrationStatementBuilder({required this.identifierPolicy});

  String buildSchema(AnalysisProject project) {
    final buffer = StringBuffer();
    buffer.writeln('-- Generated by access_to_dart');
    buffer.writeln('-- Source: ${project.source}');
    buffer.writeln(
      '-- Identifier style: ${identifierPolicy.style.cliValue}',
    );
    buffer.writeln();

    for (final table in project.tables) {
      buffer.writeln(buildCreateTableStatement(table));
      buffer.writeln();
    }
    return buffer.toString();
  }

  String buildSeed(
    AnalysisProject project, {
    Map<String, List<Map<String, dynamic>>>? tableRowsByName,
  }) {
    final buffer = StringBuffer();
    buffer.writeln('-- Generated by access_to_dart');
    buffer.writeln('-- Source: ${project.source}');
    buffer.writeln(
      '-- Identifier style: ${identifierPolicy.style.cliValue}',
    );
    buffer.writeln();

    for (final table in project.tables) {
      final rows = tableRowsByName?[table.name] ?? table.sampleRows;
      if (rows.isEmpty) {
        continue;
      }
      for (final statement in buildInsertStatements(table, rows)) {
        buffer.writeln(statement);
      }
      buffer.writeln();
    }

    return buffer.toString();
  }

  String buildCreateTableStatement(AnalysisTable table) {
    final lines = <String>[];
    final primaryKeyColumns = <String>{
      ...?table.primaryKey?.columns.map((column) => column.name),
    };

    for (final column in table.columns) {
      final isPrimaryKey = primaryKeyColumns.contains(column.name);
      final notNull = isPrimaryKey ? ' NOT NULL' : '';
      final autoInc = column.isAutoNumber ? ' GENERATED ALWAYS AS IDENTITY' : '';
      lines.add(
        '  ${identifierPolicy.quotedColumnName(column.name)} ${_postgresType(column)}$notNull$autoInc',
      );
    }

    if (primaryKeyColumns.isNotEmpty) {
      final keyColumns = table.primaryKey!.columns
          .map((column) => identifierPolicy.quotedColumnName(column.name))
          .join(', ');
      lines.add('  PRIMARY KEY ($keyColumns)');
    }

    return 'CREATE TABLE ${identifierPolicy.quotedTableName(table.name)} (\n${lines.join(',\n')}\n);';
  }

  Iterable<String> buildInsertStatements(
    AnalysisTable table,
    Iterable<Map<String, dynamic>> rows,
  ) sync* {
    for (final row in rows) {
      final columnNames = <String>[];
      final values = <String>[];

      row.forEach((key, value) {
        columnNames.add(identifierPolicy.quotedColumnName(key));
        values.add(sqlLiteral(value));
      });

      if (columnNames.isEmpty) {
        continue;
      }

      yield 'INSERT INTO ${identifierPolicy.quotedTableName(table.name)} (${columnNames.join(', ')}) VALUES (${values.join(', ')});';
    }
  }

  String sqlLiteral(Object? value) {
    if (value == null) {
      return 'NULL';
    }
    if (value is bool) {
      return value ? 'TRUE' : 'FALSE';
    }
    if (value is num) {
      return '$value';
    }
    if (value is DateTime) {
      return "'${value.toUtc().toIso8601String()}'";
    }
    if (value is Uint8List) {
      return "'\\x${_bytesToHex(value)}'";
    }
    if (value is List<int>) {
      return "'\\x${_bytesToHex(Uint8List.fromList(value))}'";
    }

    final text = value.toString().replaceAll("'", "''");
    return "'$text'";
  }

  String _postgresType(AnalysisColumn column) {
    final normalized = foldToAscii(column.typeName).toLowerCase();
    switch (normalized) {
      case 'byte':
      case 'int':
      case 'integer':
      case 'long':
      case 'complextype':
        return 'INTEGER';
      case 'double':
      case 'float':
        return 'DOUBLE PRECISION';
      case 'numeric':
        return _numericType(column);
      case 'money':
        return 'NUMERIC(19,2)';
      case 'currency':
      case 'smallmoney':
        return 'NUMERIC(19,4)';
      case 'datetime':
        return 'TIMESTAMP';
      case 'yesno':
      case 'boolean':
      case 'bit':
        return 'BOOLEAN';
      case 'binary':
      case 'longbinary':
        return 'BYTEA';
      case 'memo':
      case 'longtext':
      case 'ntext':
      case 'text':
      case 'char':
      case 'nchar':
      case 'nvarchar':
        return 'TEXT';
      case 'uniqueidentifier':
        return 'UUID';
      default:
        return 'TEXT';
    }
  }

  String _numericType(AnalysisColumn column) {
    final precision = column.precision;
    final scale = column.scale;
    if (precision != null && scale != null && precision > 0 && scale >= 0) {
      return 'NUMERIC($precision,$scale)';
    }
    if (precision != null && precision > 0) {
      return 'NUMERIC($precision)';
    }
    return 'NUMERIC';
  }

  String _bytesToHex(Uint8List bytes) {
    final buffer = StringBuffer();
    for (final value in bytes) {
      buffer.write(value.toRadixString(16).padLeft(2, '0'));
    }
    return buffer.toString();
  }
}