import 'dart:typed_data';

import 'package:jackcess_dart/jackcess_dart.dart';

import 'access_default_semantics.dart';
import 'access_temporal_semantics.dart';
import 'analysis_model.dart';
import 'identifier_utils.dart';
import 'migration_auto_number_mode.dart';
import 'migration_export_mode.dart';
import 'migration_identifier_style.dart';
import 'migration_not_null_mode.dart';
import 'migration_seed_format.dart';
import 'migration_unique_mode.dart';

class MigrationStatementBuilder {
  final MigrationIdentifierPolicy identifierPolicy;
  final MigrationAutoNumberMode autoNumberMode;
  final MigrationNotNullMode notNullMode;
  final MigrationUniqueMode uniqueMode;
  static const AccessDefaultSemanticTranslator _defaultTranslator =
      AccessDefaultSemanticTranslator();

  const MigrationStatementBuilder({
    required this.identifierPolicy,
    this.autoNumberMode = MigrationAutoNumberMode.plainInt,
    this.notNullMode = MigrationNotNullMode.relaxNotNull,
    this.uniqueMode = MigrationUniqueMode.relaxUnique,
  });

  String buildSchema(
    AnalysisProject project, {
    MigrationExportMode exportMode = MigrationExportMode.schemaAndData,
    Map<String, List<Map<String, dynamic>>>? tableRowsByName,
  }) {
    final buffer = StringBuffer();
    buffer.writeln('-- Generated by access_to_dart');
    buffer.writeln('-- Source: ${project.source}');
    buffer.writeln(
      '-- Identifier style: ${identifierPolicy.style.cliValue}',
    );
    buffer.writeln('-- Export mode: ${exportMode.cliValue}');
    buffer.writeln('-- Auto-number mode: ${autoNumberMode.cliValue}');
    buffer.writeln('-- Not-null mode: ${notNullMode.cliValue}');
    buffer.writeln('-- Unique mode: ${uniqueMode.cliValue}');
    buffer.writeln();

    for (final statement in buildPreDataStatements(
      project,
      tableRowsByName: tableRowsByName,
    )) {
      buffer.writeln(statement);
      buffer.writeln();
    }
    for (final statement in buildPostDataStatements(
      project,
      tableRowsByName: tableRowsByName,
    )) {
      buffer.writeln(statement);
      buffer.writeln();
    }
    return buffer.toString();
  }

  List<String> buildPreDataStatements(
    AnalysisProject project, {
    Map<String, List<Map<String, dynamic>>>? tableRowsByName,
  }) {
    final statements = <String>[];
    if (_requiresPgcryptoExtension(project)) {
      statements.add('CREATE EXTENSION IF NOT EXISTS pgcrypto;');
    }
    if (_usesSequences) {
      statements.addAll(buildSequenceStatements(project));
    }
    for (final table in project.tables) {
      statements.add(
        buildCreateTableStatement(
          table,
          rows: tableRowsByName?[table.name],
        ),
      );
    }
    if (_usesSequences) {
      statements.addAll(buildSequenceOwnershipStatements(project));
    }
    return statements;
  }

  List<String> buildPostDataStatements(
    AnalysisProject project, {
    Map<String, List<Map<String, dynamic>>>? tableRowsByName,
  }) {
    final statements = <String>[];
    if (_usesSequences) {
      statements.addAll(buildSequenceSyncStatements(project));
    }
    statements.addAll(
      buildIndexStatements(project, tableRowsByName: tableRowsByName),
    );
    statements.addAll(
      buildForeignKeyStatements(project, tableRowsByName: tableRowsByName),
    );
    return statements;
  }

  List<String> buildPreInsertStatements(
    AnalysisProject project, {
    Map<String, List<Map<String, dynamic>>>? tableRowsByName,
  }) {
    if (!_usesSequences) {
      return const <String>[];
    }
    final statements = <String>[];
    for (final table in project.tables) {
      final rows = tableRowsByName?[table.name];
      if (rows == null || rows.isEmpty) {
        continue;
      }
      for (final column in table.columns) {
        if (!column.isAutoNumber) {
          continue;
        }
        final maxValue = _maxAutoNumberValue(rows, column.name);
        if (maxValue == null) {
          continue;
        }
        statements.add(
          'SELECT setval(${_regclassReference(_sequenceName(table, column))}, $maxValue, true);',
        );
      }
    }
    return statements;
  }

  String buildSeed(
    AnalysisProject project, {
    MigrationSeedFormat seedFormat = MigrationSeedFormat.insert,
    Map<String, List<Map<String, dynamic>>>? tableRowsByName,
  }) {
    final buffer = StringBuffer();
    buffer.writeln('-- Generated by access_to_dart');
    buffer.writeln('-- Source: ${project.source}');
    buffer.writeln(
      '-- Identifier style: ${identifierPolicy.style.cliValue}',
    );
    buffer.writeln('-- Auto-number mode: ${autoNumberMode.cliValue}');
    buffer.writeln('-- Not-null mode: ${notNullMode.cliValue}');
    buffer.writeln('-- Unique mode: ${uniqueMode.cliValue}');
    buffer.writeln('-- Seed format: ${seedFormat.cliValue}');
    buffer.writeln();
    for (final statement
        in buildPreInsertStatements(project, tableRowsByName: tableRowsByName)) {
      buffer.writeln(statement);
    }
    if (tableRowsByName != null && tableRowsByName.isNotEmpty) {
      buffer.writeln();
    }

    for (final table in project.tables) {
      final rows = tableRowsByName?[table.name] ?? table.sampleRows;
      if (rows.isEmpty) {
        continue;
      }
      final statements = seedFormat == MigrationSeedFormat.copy
          ? buildSeedStatementsInPreferredFormat(table, rows)
          : buildInsertStatements(table, rows);
      for (final statement in statements) {
        buffer.writeln(statement);
      }
      buffer.writeln();
    }

    return buffer.toString();
  }

  String buildCreateTableStatement(
    AnalysisTable table, {
    List<Map<String, dynamic>>? rows,
  }) {
    final lines = <String>[];
    final observedRows = rows ?? table.sampleRows;
    final primaryKeyColumns = <String>{
      ...?table.primaryKey?.columns.map((column) => column.name),
    };
    final emitPrimaryKeyConstraint = _shouldEmitPrimaryKeyConstraint(
      table,
      rows,
    );
    final columnsByLookup = <String, AnalysisColumn>{
      for (final column in table.columns) _columnLookupKey(column.name): column,
    };

    for (final column in table.columns) {
      final isPrimaryKey =
          emitPrimaryKeyConstraint && primaryKeyColumns.contains(column.name);
      final generatedExpression =
          column.isCalculated
              ? _postgresCalculatedExpression(
                  column,
                  columnsByLookup,
                  rows: observedRows,
                )
              : null;
      if (generatedExpression != null) {
        lines.add(
          '  ${identifierPolicy.quotedColumnName(column.name)} ${_postgresType(column, rows: observedRows)} GENERATED ALWAYS AS ($generatedExpression) STORED',
        );
        continue;
      }
      final notNull =
          _shouldEmitNotNullConstraint(column, isPrimaryKey) ? ' NOT NULL' : '';
      final defaultExpression =
          column.isAutoNumber && _usesSequences
              ? _postgresSequenceDefault(table, column)
            : _postgresDefaultExpression(column, rows: observedRows);
      final defaultClause =
          defaultExpression == null ? '' : ' DEFAULT $defaultExpression';
      lines.add(
        '  ${identifierPolicy.quotedColumnName(column.name)} ${_postgresType(column, rows: observedRows)}$notNull$defaultClause',
      );
    }

    if (emitPrimaryKeyConstraint && primaryKeyColumns.isNotEmpty) {
      final keyColumns = table.primaryKey!.columns
          .map((column) => identifierPolicy.quotedColumnName(column.name))
          .join(', ');
      lines.add('  PRIMARY KEY ($keyColumns)');
    }

    return 'CREATE TABLE ${identifierPolicy.quotedTableName(table.name)} (\n${lines.join(',\n')}\n);';
  }

  List<String> buildSequenceStatements(AnalysisProject project) {
    final statements = <String>[];
    for (final table in project.tables) {
      for (final column in table.columns) {
        if (!column.isAutoNumber) {
          continue;
        }
        statements.add(
          'CREATE SEQUENCE IF NOT EXISTS ${_quotedDbObjectName(_sequenceName(table, column))};',
        );
      }
    }
    return statements;
  }

  List<String> buildSequenceOwnershipStatements(AnalysisProject project) {
    final statements = <String>[];
    for (final table in project.tables) {
      for (final column in table.columns) {
        if (!column.isAutoNumber) {
          continue;
        }
        statements.add(
          'ALTER SEQUENCE ${_quotedDbObjectName(_sequenceName(table, column))} '
          'OWNED BY ${identifierPolicy.quotedTableName(table.name)}.${identifierPolicy.quotedColumnName(column.name)};',
        );
      }
    }
    return statements;
  }

  List<String> buildSequenceSyncStatements(AnalysisProject project) {
    final statements = <String>[];
    for (final table in project.tables) {
      for (final column in table.columns) {
        if (!column.isAutoNumber) {
          continue;
        }
        final regclass = _regclassReference(_sequenceName(table, column));
        final quotedColumn = identifierPolicy.quotedColumnName(column.name);
        statements.add(
          'SELECT setval($regclass, COALESCE(MAX($quotedColumn), 1), MAX($quotedColumn) IS NOT NULL) '
          'FROM ${identifierPolicy.quotedTableName(table.name)};',
        );
      }
    }
    return statements;
  }

  List<String> buildForeignKeyStatements(
    AnalysisProject project, {
    Map<String, List<Map<String, dynamic>>>? tableRowsByName,
  }) {
    final tableNames = <String>{for (final table in project.tables) table.name};
    final tablesByName = {
      for (final table in project.tables) table.name: table,
    };
    final statements = <String>[];
    for (final relationship in project.relationships) {
      if (!tableNames.contains(relationship.fromTable) ||
          !tableNames.contains(relationship.toTable) ||
          relationship.fromColumns.isEmpty ||
          relationship.toColumns.isEmpty ||
          relationship.fromColumns.length != relationship.toColumns.length) {
        continue;
      }
      if (!_shouldEmitForeignKeyConstraint(
        relationship,
        tablesByName: tablesByName,
        tableRowsByName: tableRowsByName,
      )) {
        continue;
      }
      final fromColumns = relationship.fromColumns
          .map(identifierPolicy.quotedColumnName)
          .join(', ');
      final toColumns = relationship.toColumns
          .map(identifierPolicy.quotedColumnName)
          .join(', ');
      statements.add(
        'ALTER TABLE ${identifierPolicy.quotedTableName(relationship.fromTable)} '
        'ADD CONSTRAINT ${_quotedDbObjectName(_constraintName(relationship))} '
        'FOREIGN KEY ($fromColumns) '
        'REFERENCES ${identifierPolicy.quotedTableName(relationship.toTable)} ($toColumns);',
      );
    }
    for (final table in project.tables.where((table) => table.isSyntheticAttachmentTable)) {
      final parentTableName = table.attachmentParentTable;
      final parentColumnName = table.attachmentParentColumn;
      final linkColumnName = table.attachmentLinkColumn;
      if (parentTableName == null ||
          parentColumnName == null ||
          linkColumnName == null ||
          !tableNames.contains(parentTableName) ||
          !table.columns.any((column) => column.name == linkColumnName)) {
        continue;
      }
      final syntheticRelationship = AnalysisRelationship(
        name: 'fk_${table.name}_${parentTableName}_attachment',
        fromTable: table.name,
        toTable: parentTableName,
        fromColumns: [linkColumnName],
        toColumns: [parentColumnName],
        flags: null,
        columnCount: 1,
      );
      if (!_shouldEmitForeignKeyConstraint(
        syntheticRelationship,
        tablesByName: tablesByName,
        tableRowsByName: tableRowsByName,
      )) {
        continue;
      }
      statements.add(
        'ALTER TABLE ${identifierPolicy.quotedTableName(table.name)} '
        'ADD CONSTRAINT ${_quotedDbObjectName(_constraintName(syntheticRelationship))} '
        'FOREIGN KEY (${identifierPolicy.quotedColumnName(linkColumnName)}) '
        'REFERENCES ${identifierPolicy.quotedTableName(parentTableName)} (${identifierPolicy.quotedColumnName(parentColumnName)});',
      );
    }
    return statements;
  }

  List<String> buildIndexStatements(
    AnalysisProject project, {
    Map<String, List<Map<String, dynamic>>>? tableRowsByName,
  }) {
    final statements = <String>[];
    for (final table in project.tables) {
      final primaryKeyColumns = <String>{
        ...?table.primaryKey?.columns.map((column) => column.name),
      };
      if (primaryKeyColumns.isNotEmpty &&
          !_shouldEmitPrimaryKeyConstraint(
            table,
            tableRowsByName?[table.name],
          )) {
        final orderedColumns = table.primaryKey!.columns
            .map(
              (column) =>
                  '${identifierPolicy.quotedColumnName(column.name)} ${column.ascending ? 'ASC' : 'DESC'}',
            )
            .join(', ');
        statements.add(
          'CREATE INDEX ${_quotedDbObjectName(_relaxedPrimaryKeyIndexName(table))} '
          'ON ${identifierPolicy.quotedTableName(table.name)} ($orderedColumns);',
        );
      }
      for (final index in table.indexes) {
        if (index.isPrimaryKey || index.columns.isEmpty) {
          continue;
        }
        final orderedColumns = index.columns
            .map(
              (column) =>
                  '${identifierPolicy.quotedColumnName(column.name)} ${column.ascending ? 'ASC' : 'DESC'}',
            )
            .join(', ');
        final unique =
            _shouldEmitUniqueIndex(table, index, tableRowsByName?[table.name])
                ? 'UNIQUE '
                : '';
        statements.add(
          'CREATE ${unique}INDEX ${_quotedDbObjectName(_indexName(table, index))} '
          'ON ${identifierPolicy.quotedTableName(table.name)} ($orderedColumns);',
        );
      }
    }
    return statements;
  }

  Iterable<String> buildInsertStatements(
    AnalysisTable table,
    Iterable<Map<String, dynamic>> rows,
  ) sync* {
    final rowList = rows.toList(growable: false);
    final columnsByName = {
      for (final column in table.columns) column.name: column,
    };
    for (final normalizedRow in normalizedRowsForInsert(table, rowList)) {
      final columnNames = normalizedRow.keys
          .map(identifierPolicy.quotedColumnName)
          .join(', ');
      final values = normalizedRow.entries
          .map(
            (entry) => sqlLiteralForColumn(
              columnsByName[entry.key],
              entry.value,
              rows: rowList,
            ),
          )
          .join(', ');
      yield 'INSERT INTO ${identifierPolicy.quotedTableName(table.name)} ($columnNames) VALUES ($values);';
    }
  }

  Iterable<String> buildSeedStatementsInPreferredFormat(
    AnalysisTable table,
    Iterable<Map<String, dynamic>> rows,
  ) sync* {
    if (!canUseCopySeedForTable(table)) {
      if (autoNumberMode == MigrationAutoNumberMode.sequence &&
          table.columns.any((column) => column.isAutoNumber)) {
        yield '-- COPY skipped for ${table.name}: preserving explicit auto-number values requires INSERT statements in sequence mode.';
      }
      yield* buildInsertStatements(table, rows);
      return;
    }

    final rowList = rows.toList(growable: false);
    final normalizedRows = normalizedRowsForInsert(table, rowList).toList();
    if (normalizedRows.isEmpty) {
      return;
    }

    final orderedColumns = copyColumnNamesForTable(table, normalizedRows);
    if (orderedColumns.isEmpty) {
      return;
    }

    final quotedColumns = orderedColumns
        .map(identifierPolicy.quotedColumnName)
        .join(', ');
    yield 'COPY ${identifierPolicy.quotedTableName(table.name)} ($quotedColumns) FROM STDIN;';
    for (final row in normalizedRows) {
      final fields = orderedColumns
          .map(
            (columnName) => _copyFieldLiteral(
              table.columns.where((column) => column.name == columnName).first,
              row[columnName],
              rows: normalizedRows,
            ),
          )
          .join('\t');
      yield fields;
    }
    yield r'\.';
  }

  Iterable<Map<String, dynamic>> normalizedRowsForInsert(
    AnalysisTable table,
    Iterable<Map<String, dynamic>> rows,
  ) sync* {
    final writableColumns = {
      for (final column in table.columns)
        if (!column.isCalculated) column.name,
    };
    final autoNumberColumns = {
      for (final column in table.columns)
        if (column.isAutoNumber) column.name: column,
    };
    final primaryKeyColumns = <String>{
      ...?table.primaryKey?.columns.map((column) => column.name),
    };
    final columnsByName = {
      for (final column in table.columns) column.name: column,
    };
    final seenPrimaryKeys = <String>{};
    var syntheticIntegerSeed = -1;
    var syntheticDoubleSeed = -1.0;
    for (final row in rows) {
      var effectiveRow = _normalizeRowForInsert(
        table,
        row,
        primaryKeyColumns: primaryKeyColumns,
        nextSyntheticInt: () => syntheticIntegerSeed--,
        nextSyntheticDouble: () {
          final current = syntheticDoubleSeed;
          syntheticDoubleSeed -= 1.0;
          return current;
        },
      );
      if (effectiveRow == null) {
        continue;
      }
      effectiveRow = _normalizePrimaryKeyForInsert(
        effectiveRow,
        columnsByName: columnsByName,
        primaryKeyColumns: primaryKeyColumns,
        seenPrimaryKeys: seenPrimaryKeys,
        nextSyntheticInt: () => syntheticIntegerSeed--,
        nextSyntheticDouble: () {
          final current = syntheticDoubleSeed;
          syntheticDoubleSeed -= 1.0;
          return current;
        },
      );
      if (effectiveRow == null) {
        continue;
      }
      final normalizedRow = <String, dynamic>{};

      effectiveRow.forEach((key, value) {
        if (!writableColumns.contains(key)) {
          return;
        }
        final autoNumberColumn = autoNumberColumns[key];
        if (autoNumberColumn != null &&
            _shouldOmitExplicitAutoNumber(autoNumberColumn, value)) {
          return;
        }
        normalizedRow[key] = value;
      });

      if (normalizedRow.isEmpty) {
        continue;
      }
      yield normalizedRow;
    }
  }

  bool canUseCopySeedForTable(AnalysisTable table) {
    if (autoNumberMode == MigrationAutoNumberMode.sequence &&
        table.columns.any((column) => column.isAutoNumber)) {
      return false;
    }
    return true;
  }

  List<String> copyColumnNamesForTable(
    AnalysisTable table,
    List<Map<String, dynamic>> normalizedRows,
  ) {
    final presentColumns = <String>{};
    for (final row in normalizedRows) {
      presentColumns.addAll(row.keys);
    }
    return [
      for (final column in table.columns)
        if (!column.isCalculated && presentColumns.contains(column.name))
          column.name,
    ];
  }

  String _copyFieldLiteral(
    AnalysisColumn column,
    Object? value, {
    Iterable<Map<String, dynamic>>? rows,
  }) {
    if (value == null) {
      return r'\N';
    }
    if (value is bool) {
      return value ? 't' : 'f';
    }
    if (value is num) {
      return '$value';
    }
    if (value is DateTime) {
      return _escapeCopyText(
        _formatTemporalValueForSql(column, value, rows: rows),
      );
    }
    if (value is Uint8List) {
      return _escapeCopyText('\\x${_bytesToHex(value)}');
    }
    if (value is List<int>) {
      return _escapeCopyText('\\x${_bytesToHex(Uint8List.fromList(value))}');
    }
    return _escapeCopyText(_postgresSafeText(value.toString()));
  }

  String _escapeCopyText(String value) {
    return value
        .replaceAll('\\', r'\\')
        .replaceAll('\t', r'\t')
        .replaceAll('\n', r'\n')
        .replaceAll('\r', r'\r');
  }

  String sqlLiteralForColumn(
    AnalysisColumn? column,
    Object? value, {
    Iterable<Map<String, dynamic>>? rows,
  }) {
    value = normalizeValueForPostgres(value);
    if (value == null) {
      return 'NULL';
    }
    if (value is bool) {
      return value ? 'TRUE' : 'FALSE';
    }
    if (value is num) {
      return '$value';
    }
    if (value is DateTime) {
      final serialized = column == null
          ? value.toUtc().toIso8601String()
          : _formatTemporalValueForSql(column, value, rows: rows);
      return "'$serialized'";
    }
    if (value is Uint8List) {
      return "'\\x${_bytesToHex(value)}'";
    }
    if (value is List<int>) {
      return "'\\x${_bytesToHex(Uint8List.fromList(value))}'";
    }

    final text = value.toString().replaceAll("'", "''");
    return "'$text'";
  }

  Object? normalizeValueForPostgres(Object? value) {
    if (value is String) {
      return _postgresSafeText(value);
    }
    return value;
  }

  String _postgresSafeText(String value) {
    final sanitized = StringBuffer();
    final units = value.codeUnits;
    for (var index = 0; index < units.length; index++) {
      final unit = units[index];
      if (unit >= 0xD800 && unit <= 0xDBFF) {
        if (index + 1 >= units.length) {
          continue;
        }
        final nextUnit = units[index + 1];
        if (nextUnit < 0xDC00 || nextUnit > 0xDFFF) {
          continue;
        }
        sanitized.write(String.fromCharCodes(<int>[unit, nextUnit]));
        index++;
        continue;
      }
      if (unit >= 0xDC00 && unit <= 0xDFFF) {
        continue;
      }
      if (unit == 0) {
        continue;
      }
      final isAllowedControl = unit == 0x09 || unit == 0x0A || unit == 0x0D;
      final isOtherControl = unit < 0x20 && !isAllowedControl;
      if (isOtherControl) {
        continue;
      }
      sanitized.writeCharCode(unit);
    }
    return sanitized.toString();
  }

  int? _maxAutoNumberValue(
    List<Map<String, dynamic>> rows,
    String columnName,
  ) {
    int? maxValue;
    for (final row in rows) {
      final value = row[columnName];
      final intValue = switch (value) {
        int() => value,
        num() => value.toInt(),
        String() => int.tryParse(value),
        _ => null,
      };
      if (intValue == null) {
        continue;
      }
      if (maxValue == null || intValue > maxValue) {
        maxValue = intValue;
      }
    }
    return maxValue;
  }

  bool _shouldOmitExplicitAutoNumber(
    AnalysisColumn column,
    Object? value,
  ) {
    if (autoNumberMode == MigrationAutoNumberMode.plainInt) {
      return false;
    }
    if (autoNumberMode == MigrationAutoNumberMode.forceSequence) {
      return true;
    }
    final numericValue = switch (value) {
      null => null,
      int() => value,
      num() => value.toInt(),
      String() => int.tryParse(value.trim()),
      _ => null,
    };
    if (numericValue == null) {
      return value == null;
    }
    return numericValue <= 0;
  }

  Map<String, dynamic>? _normalizeRowForInsert(
    AnalysisTable table,
    Map<String, dynamic> row, {
    required Set<String> primaryKeyColumns,
    required int Function() nextSyntheticInt,
    required double Function() nextSyntheticDouble,
  }) {
    if (notNullMode == MigrationNotNullMode.strict ||
        notNullMode == MigrationNotNullMode.relaxNotNull) {
      return row;
    }

    final normalized = Map<String, dynamic>.from(row);
    var hasInvalidRequired = false;
    for (final column in table.columns) {
      if (column.isCalculated) {
        continue;
      }
      final isPrimaryKey = primaryKeyColumns.contains(column.name);
      final isRequired = isPrimaryKey || column.isRequired;
      if (!isRequired) {
        continue;
      }
      final currentValue = normalized[column.name];
      final invalid = _isInvalidRequiredValue(currentValue);
      if (!invalid) {
        continue;
      }
      hasInvalidRequired = true;
      if (notNullMode == MigrationNotNullMode.skipRow) {
        return null;
      }
      if (notNullMode == MigrationNotNullMode.fix) {
        normalized[column.name] = _fixValueForRequiredColumn(
          column,
          nextSyntheticInt: nextSyntheticInt,
          nextSyntheticDouble: nextSyntheticDouble,
        );
      }
    }

    if (notNullMode == MigrationNotNullMode.skipRow && hasInvalidRequired) {
      return null;
    }
    return normalized;
  }

  Map<String, dynamic>? _normalizePrimaryKeyForInsert(
    Map<String, dynamic> row, {
    required Map<String, AnalysisColumn> columnsByName,
    required Set<String> primaryKeyColumns,
    required Set<String> seenPrimaryKeys,
    required int Function() nextSyntheticInt,
    required double Function() nextSyntheticDouble,
  }) {
    if (primaryKeyColumns.isEmpty) {
      return row;
    }

    final keyParts = <String>[];
    var missingPrimaryKeyValue = false;
    for (final columnName in primaryKeyColumns) {
      final value = row[columnName];
      if (_isInvalidRequiredValue(value)) {
        missingPrimaryKeyValue = true;
      }
      keyParts.add(_primaryKeyComponent(value));
    }
    final key = keyParts.join('|');
    final duplicatePrimaryKey = seenPrimaryKeys.contains(key);
    if (!missingPrimaryKeyValue && !duplicatePrimaryKey) {
      seenPrimaryKeys.add(key);
      return row;
    }

    if (notNullMode == MigrationNotNullMode.skipRow) {
      return null;
    }
    if (notNullMode != MigrationNotNullMode.fix) {
      return row;
    }

    final normalized = Map<String, dynamic>.from(row);
    for (final columnName in primaryKeyColumns) {
      final column = columnsByName[columnName];
      if (column == null) {
        continue;
      }
      normalized[columnName] = _fixValueForRequiredColumn(
        column,
        nextSyntheticInt: nextSyntheticInt,
        nextSyntheticDouble: nextSyntheticDouble,
      );
    }

    final repairedKey = primaryKeyColumns
        .map((columnName) => _primaryKeyComponent(normalized[columnName]))
        .join('|');
    seenPrimaryKeys.add(repairedKey);
    return normalized;
  }

  bool _isInvalidRequiredValue(Object? value) {
    if (value == null) {
      return true;
    }
    if (value is String) {
      return value.isEmpty;
    }
    return false;
  }

  String _primaryKeyComponent(Object? value) {
    if (value == null) {
      return '<null>';
    }
    if (value is DateTime) {
      return value.toUtc().toIso8601String();
    }
    return value.toString();
  }

  Object _fixValueForRequiredColumn(
    AnalysisColumn column, {
    required int Function() nextSyntheticInt,
    required double Function() nextSyntheticDouble,
  }) {
    final normalized = foldToAscii(column.typeName).toLowerCase();
    switch (normalized) {
      case 'byte':
      case 'int':
      case 'integer':
      case 'long':
      case 'complextype':
        return nextSyntheticInt();
      case 'double':
      case 'float':
      case 'numeric':
      case 'money':
      case 'currency':
      case 'smallmoney':
        return nextSyntheticDouble();
      case 'datetime':
      case 'date':
      case 'time':
        return DateTime.now().toUtc();
      case 'yesno':
      case 'boolean':
      case 'bit':
        return false;
      case 'uniqueidentifier':
      case 'guid':
        return '00000000-0000-0000-0000-000000000000';
      default:
        return '';
    }
  }

  bool _shouldEmitNotNullConstraint(
    AnalysisColumn column,
    bool isPrimaryKey,
  ) {
    if (isPrimaryKey) {
      return true;
    }
    if (!column.isRequired) {
      return false;
    }
    return notNullMode != MigrationNotNullMode.relaxNotNull;
  }

  bool _shouldEmitPrimaryKeyConstraint(
    AnalysisTable table,
    List<Map<String, dynamic>>? rows,
  ) {
    final primaryKeyColumns = <String>{
      ...?table.primaryKey?.columns.map((column) => column.name),
    };
    if (primaryKeyColumns.isEmpty) {
      return false;
    }
    if (notNullMode != MigrationNotNullMode.relaxNotNull ||
        rows == null ||
        rows.isEmpty) {
      return true;
    }

    final seenKeys = <String>{};
    for (final row in rows) {
      final keyParts = <String>[];
      var missingValue = false;
      for (final columnName in primaryKeyColumns) {
        final value = row[columnName];
        if (_isInvalidRequiredValue(value)) {
          missingValue = true;
          break;
        }
        keyParts.add(_primaryKeyComponent(value));
      }
      if (missingValue) {
        return false;
      }
      final key = keyParts.join('|');
      if (!seenKeys.add(key)) {
        return false;
      }
    }
    return true;
  }

  bool _shouldEmitForeignKeyConstraint(
    AnalysisRelationship relationship, {
    required Map<String, AnalysisTable> tablesByName,
    required Map<String, List<Map<String, dynamic>>>? tableRowsByName,
  }) {
    if (notNullMode != MigrationNotNullMode.relaxNotNull ||
        tableRowsByName == null) {
      return true;
    }

    final targetTable = tablesByName[relationship.toTable];
    if (targetTable == null) {
      return false;
    }
    final targetRows = tableRowsByName[relationship.toTable];
    if (!_hasEnforceableTargetKey(
      targetTable,
      relationship.toColumns,
      targetRows,
    )) {
      return false;
    }

    final targetKeyRows = targetRows ?? const <Map<String, dynamic>>[];
    final targetKeys = <String>{};
    for (final row in targetKeyRows) {
      final key = _relationshipKey(row, relationship.toColumns);
      if (key != null) {
        targetKeys.add(key);
      }
    }

    final sourceRows = tableRowsByName[relationship.fromTable] ?? const [];
    for (final row in sourceRows) {
      final key = _relationshipKey(row, relationship.fromColumns);
      if (key == null) {
        continue;
      }
      if (!targetKeys.contains(key)) {
        return false;
      }
    }

    return true;
  }

  bool _hasEnforceableTargetKey(
    AnalysisTable table,
    List<String> targetColumns,
    List<Map<String, dynamic>>? rows,
  ) {
    final primaryKeyColumns = table.primaryKey?.columns
        .map((column) => column.name)
        .toList(growable: false);
    if (_sameColumnSet(primaryKeyColumns, targetColumns)) {
      return _shouldEmitPrimaryKeyConstraint(table, rows);
    }

    for (final index in table.indexes) {
      if (!index.isUnique || index.columns.isEmpty) {
        continue;
      }
      final indexColumns = index.columns
          .map((column) => column.name)
          .toList(growable: false);
      if (_sameColumnSet(indexColumns, targetColumns) &&
          _shouldEmitUniqueIndex(table, index, rows)) {
        return true;
      }
    }
    return false;
  }

  bool _sameColumnSet(List<String>? left, List<String> right) {
    if (left == null || left.length != right.length) {
      return false;
    }
    for (var index = 0; index < left.length; index++) {
      if (left[index] != right[index]) {
        return false;
      }
    }
    return true;
  }

  bool _shouldEmitUniqueIndex(
    AnalysisTable table,
    AnalysisIndex index,
    List<Map<String, dynamic>>? rows,
  ) {
    if (!index.isUnique) {
      return false;
    }
    if (uniqueMode != MigrationUniqueMode.relaxUnique ||
        rows == null ||
        rows.isEmpty) {
      return true;
    }

    final indexedColumns = index.columns
        .map((column) => column.name)
        .toList(growable: false);
    final primaryKeyColumns = table.primaryKey?.columns
        .map((column) => column.name)
        .toList(growable: false);
    if (_sameColumnSet(primaryKeyColumns, indexedColumns) &&
        !_shouldEmitPrimaryKeyConstraint(table, rows)) {
      return false;
    }

    final seenKeys = <String>{};
    for (final row in rows) {
      final key = _uniqueIndexKey(row, indexedColumns);
      if (key == null) {
        continue;
      }
      if (!seenKeys.add(key)) {
        return false;
      }
    }
    return true;
  }

  String? _uniqueIndexKey(
    Map<String, dynamic> row,
    List<String> columns,
  ) {
    final parts = <String>[];
    for (final columnName in columns) {
      final value = row[columnName];
      if (value == null) {
        return null;
      }
      parts.add(_primaryKeyComponent(value));
    }
    return parts.join('|');
  }

  String? _relationshipKey(
    Map<String, dynamic> row,
    List<String> columns,
  ) {
    final parts = <String>[];
    for (final columnName in columns) {
      final value = row[columnName];
      if (_isInvalidRequiredValue(value)) {
        return null;
      }
      parts.add(_primaryKeyComponent(value));
    }
    return parts.join('|');
  }

  String _relaxedPrimaryKeyIndexName(AnalysisTable table) {
    return 'idx_${table.name}_pk_relaxed';
  }

  bool get _usesSequences => autoNumberMode != MigrationAutoNumberMode.plainInt;

  String _postgresType(
    AnalysisColumn column, {
    Iterable<Map<String, dynamic>>? rows,
  }) {
    final normalized = foldToAscii(column.typeName).toLowerCase();
    switch (normalized) {
      case 'byte':
      case 'int':
      case 'integer':
      case 'long':
      case 'complextype':
        return 'INTEGER';
      case 'double':
      case 'float':
        return 'DOUBLE PRECISION';
      case 'numeric':
        return _numericType(column);
      case 'money':
        return 'NUMERIC(19,2)';
      case 'currency':
      case 'smallmoney':
        return 'NUMERIC(19,4)';
      case 'date':
      case 'time':
      case 'datetime':
        return _postgresTemporalTypeForColumn(column, rows: rows);
      case 'yesno':
      case 'boolean':
      case 'bit':
        return 'BOOLEAN';
      case 'binary':
      case 'longbinary':
      case 'ole':
        return 'BYTEA';
      case 'memo':
      case 'longtext':
      case 'ntext':
      case 'text':
      case 'char':
      case 'nchar':
      case 'nvarchar':
        return 'TEXT';
      case 'uniqueidentifier':
      case 'guid':
        return 'UUID';
      default:
        return 'TEXT';
    }
  }

  String _numericType(AnalysisColumn column) {
    final precision = column.precision;
    final scale = column.scale;
    if (precision != null && scale != null && precision > 0 && scale >= 0) {
      return 'NUMERIC($precision,$scale)';
    }
    if (precision != null && precision > 0) {
      return 'NUMERIC($precision)';
    }
    return 'NUMERIC';
  }

  String _postgresSequenceDefault(AnalysisTable table, AnalysisColumn column) {
    return 'nextval(${_regclassReference(_sequenceName(table, column))})';
  }

  String? _postgresDefaultExpression(
    AnalysisColumn column, {
    Iterable<Map<String, dynamic>>? rows,
  }) {
    return _defaultTranslator.translate(column, rows: rows)?.postgresExpression;
  }

  String? _postgresCalculatedExpression(
    AnalysisColumn column,
    Map<String, AnalysisColumn> columnsByLookup, {
    Iterable<Map<String, dynamic>>? rows,
  }
  ) {
    final expression = column.calculatedExpression?.trim();
    if (expression == null || expression.isEmpty) {
      return null;
    }
    final parsed = AccessExpressionParser.tryParse(expression);
    if (parsed == null) {
      return null;
    }
    final translated = _translateAccessNode(
      parsed,
      columnsByLookup,
      rows: rows,
    );
    if (translated == null) {
      return null;
    }
    return _coerceCalculatedExpressionForColumn(
      translated,
      column,
      rows: rows,
    );
  }

  _TranslatedCalculatedExpression? _translateAccessNode(
    AccessExpressionNode node,
    Map<String, AnalysisColumn> columnsByLookup, {
    Iterable<Map<String, dynamic>>? rows,
  }
  ) {
    if (node is AccessIdentifierNode) {
      if (node.parts.isEmpty || node.parts.last == '*') {
        return null;
      }
      final resolved = _resolveColumn(node.parts.last, columnsByLookup);
      return _TranslatedCalculatedExpression(
        sql: identifierPolicy.quotedColumnName(node.parts.last),
        kind: _expressionKindForColumn(resolved, rows: rows),
      );
    }
    if (node is AccessStringNode) {
      return _TranslatedCalculatedExpression(
        sql: _singleQuotedLiteral(node.value),
        kind: _CalculatedExpressionKind.text,
      );
    }
    if (node is AccessNumberNode) {
      return _TranslatedCalculatedExpression(
        sql: node.value,
        kind: _CalculatedExpressionKind.number,
      );
    }
    if (node is AccessUnaryNode) {
      final operand = _translateAccessNode(
        node.operand,
        columnsByLookup,
        rows: rows,
      );
      if (operand == null) {
        return null;
      }
      final op =
          node.operatorName.toUpperCase() == 'NOT' ? 'NOT ' : node.operatorName;
      return _TranslatedCalculatedExpression(
        sql: '($op${operand.sql})',
        kind: node.operatorName.toUpperCase() == 'NOT'
            ? _CalculatedExpressionKind.booleanValue
            : operand.kind,
      );
    }
    if (node is AccessBinaryNode) {
      final left = _translateAccessNode(node.left, columnsByLookup, rows: rows);
      final right = _translateAccessNode(node.right, columnsByLookup, rows: rows);
      if (left == null || right == null) {
        return null;
      }
      return _translateBinaryNode(node, left, right);
    }
    if (node is AccessFunctionCallNode) {
      final name = foldToAscii(node.name).toUpperCase();
      final args = node.arguments
          .map(
          (argument) =>
            _translateAccessNode(argument, columnsByLookup, rows: rows),
          )
          .toList(growable: false);
      if (args.any((arg) => arg == null)) {
        return null;
      }
      final translatedArgs = args.cast<_TranslatedCalculatedExpression>();
      switch (name) {
        case 'NZ':
          if (translatedArgs.length == 1) {
            return _TranslatedCalculatedExpression(
              sql: 'COALESCE(${translatedArgs[0].sql}, \'\')',
              kind: translatedArgs[0].kind == _CalculatedExpressionKind.unknown
                  ? _CalculatedExpressionKind.text
                  : translatedArgs[0].kind,
            );
          }
          if (translatedArgs.length == 2) {
            return _TranslatedCalculatedExpression(
              sql:
                  'COALESCE(${translatedArgs[0].sql}, ${translatedArgs[1].sql})',
              kind: translatedArgs[0].kind != _CalculatedExpressionKind.unknown
                  ? translatedArgs[0].kind
                  : translatedArgs[1].kind,
            );
          }
          return null;
        case 'IIF':
          if (translatedArgs.length != 3) {
            return null;
          }
          return _TranslatedCalculatedExpression(
            sql:
                '(CASE WHEN ${translatedArgs[0].sql} THEN ${translatedArgs[1].sql} ELSE ${translatedArgs[2].sql} END)',
            kind: translatedArgs[1].kind != _CalculatedExpressionKind.unknown
                ? translatedArgs[1].kind
                : translatedArgs[2].kind,
          );
        case 'LEN':
          if (translatedArgs.length != 1) {
            return null;
          }
          return _TranslatedCalculatedExpression(
            sql: 'CHAR_LENGTH(${translatedArgs[0].sql})',
            kind: _CalculatedExpressionKind.number,
          );
        case 'ABS':
        case 'ROUND':
        case 'UCASE':
        case 'LCASE':
          final targetName = switch (name) {
            'UCASE' => 'UPPER',
            'LCASE' => 'LOWER',
            _ => name,
          };
          final kind = switch (name) {
            'UCASE' || 'LCASE' => _CalculatedExpressionKind.text,
            _ => translatedArgs.isEmpty
                ? _CalculatedExpressionKind.unknown
                : translatedArgs.first.kind,
          };
          return _TranslatedCalculatedExpression(
            sql:
                '$targetName(${translatedArgs.map((arg) => arg.sql).join(', ')})',
            kind: kind,
          );
        case 'ISNULL':
          if (translatedArgs.length != 1) {
            return null;
          }
          return _TranslatedCalculatedExpression(
            sql: '(${translatedArgs[0].sql} IS NULL)',
            kind: _CalculatedExpressionKind.booleanValue,
          );
        default:
          return null;
      }
    }
    return null;
  }

  _TranslatedCalculatedExpression? _translateBinaryNode(
    AccessBinaryNode node,
    _TranslatedCalculatedExpression left,
    _TranslatedCalculatedExpression right,
  ) {
    final operatorName = node.operatorName.toUpperCase();
    switch (operatorName) {
      case '&':
        return _TranslatedCalculatedExpression(
          sql: '(${left.sql} || ${right.sql})',
          kind: _CalculatedExpressionKind.text,
        );
      case '=':
      case '<>':
      case '>':
      case '<':
      case '>=':
      case '<=':
        final op = switch (operatorName) {
          '=' => '=',
          '<>' => '!=',
          '>' => '>',
          '<' => '<',
          '>=' => '>=',
          '<=' => '<=',
          _ => '',
        };
        return _TranslatedCalculatedExpression(
          sql: '(${left.sql} $op ${right.sql})',
          kind: _CalculatedExpressionKind.booleanValue,
        );
      case 'AND':
      case 'OR':
        return _TranslatedCalculatedExpression(
          sql: '(${left.sql} $operatorName ${right.sql})',
          kind: _CalculatedExpressionKind.booleanValue,
        );
      case '+':
      case '-':
        return _translateAdditiveNode(operatorName, left, right);
      case '*':
      case '/':
        return _TranslatedCalculatedExpression(
          sql: '(${left.sql} $operatorName ${right.sql})',
          kind: _inferArithmeticKind(left.kind, right.kind),
        );
      default:
        return null;
    }
  }

  _TranslatedCalculatedExpression? _translateAdditiveNode(
    String operatorName,
    _TranslatedCalculatedExpression left,
    _TranslatedCalculatedExpression right,
  ) {
    final leftIsDateLike = _isDateLikeKind(left.kind);
    final rightIsDateLike = _isDateLikeKind(right.kind);
    final leftIsNumber = left.kind == _CalculatedExpressionKind.number;
    final rightIsNumber = right.kind == _CalculatedExpressionKind.number;

    if (leftIsDateLike && rightIsNumber) {
      return _TranslatedCalculatedExpression(
        sql:
            '(${left.sql} $operatorName (${right.sql}) * INTERVAL \'1 day\')',
        kind: left.kind,
      );
    }
    if (operatorName == '+' && leftIsNumber && rightIsDateLike) {
      return _TranslatedCalculatedExpression(
        sql: '(${right.sql} + (${left.sql}) * INTERVAL \'1 day\')',
        kind: right.kind,
      );
    }
    return _TranslatedCalculatedExpression(
      sql: '(${left.sql} $operatorName ${right.sql})',
      kind: _inferArithmeticKind(left.kind, right.kind),
    );
  }

  String _coerceCalculatedExpressionForColumn(
    _TranslatedCalculatedExpression expression,
    AnalysisColumn column, {
    Iterable<Map<String, dynamic>>? rows,
  }
  ) {
    final targetKind = _expressionKindForColumn(column, rows: rows);
    return switch (targetKind) {
      _CalculatedExpressionKind.datetime => '(${expression.sql})::timestamp',
      _CalculatedExpressionKind.dateValue => '(${expression.sql})::date',
      _CalculatedExpressionKind.timeValue => '(${expression.sql})::time',
      _ => expression.sql,
    };
  }

  AnalysisColumn? _resolveColumn(
    String rawName,
    Map<String, AnalysisColumn> columnsByLookup,
  ) {
    return columnsByLookup[_columnLookupKey(rawName)];
  }

  String _columnLookupKey(String rawName) {
    return foldToAscii(rawName).toLowerCase();
  }

  _CalculatedExpressionKind _expressionKindForColumn(
    AnalysisColumn? column, {
    Iterable<Map<String, dynamic>>? rows,
  }) {
    if (column == null) {
      return _CalculatedExpressionKind.unknown;
    }
    final temporalSemantic = _temporalSemanticForColumn(column, rows: rows);
    switch (temporalSemantic) {
      case AccessTemporalSemantic.timestamp:
        return _CalculatedExpressionKind.datetime;
      case AccessTemporalSemantic.dateOnly:
        return _CalculatedExpressionKind.dateValue;
      case AccessTemporalSemantic.timeOnly:
        return _CalculatedExpressionKind.timeValue;
      case AccessTemporalSemantic.unknown:
        break;
    }
    final normalized = foldToAscii(column.typeName).toLowerCase();
    switch (normalized) {
      case 'date':
        return _CalculatedExpressionKind.dateValue;
      case 'time':
        return _CalculatedExpressionKind.timeValue;
      case 'yesno':
      case 'boolean':
      case 'bit':
        return _CalculatedExpressionKind.booleanValue;
      case 'byte':
      case 'int':
      case 'integer':
      case 'long':
      case 'double':
      case 'float':
      case 'numeric':
      case 'money':
      case 'currency':
      case 'smallmoney':
      case 'complextype':
        return _CalculatedExpressionKind.number;
      case 'memo':
      case 'longtext':
      case 'ntext':
      case 'text':
      case 'char':
      case 'nchar':
      case 'nvarchar':
        return _CalculatedExpressionKind.text;
      default:
        return _CalculatedExpressionKind.unknown;
    }
  }

  bool _isDateLikeKind(_CalculatedExpressionKind kind) {
    return kind == _CalculatedExpressionKind.datetime ||
        kind == _CalculatedExpressionKind.dateValue ||
        kind == _CalculatedExpressionKind.timeValue;
  }

  String _postgresTemporalTypeForColumn(
    AnalysisColumn column, {
    Iterable<Map<String, dynamic>>? rows,
  }) {
    return switch (_temporalSemanticForColumn(column, rows: rows)) {
      AccessTemporalSemantic.dateOnly => 'DATE',
      AccessTemporalSemantic.timeOnly => 'TIME',
      _ => 'TIMESTAMP',
    };
  }

  String _formatTemporalValueForSql(
    AnalysisColumn column,
    DateTime value, {
    Iterable<Map<String, dynamic>>? rows,
  }) {
    final utc = value.toUtc();
    return switch (_temporalSemanticForColumn(column, rows: rows)) {
      AccessTemporalSemantic.dateOnly => _formatDateOnly(utc),
      AccessTemporalSemantic.timeOnly => _formatTimeOnly(utc),
      _ => utc.toIso8601String(),
    };
  }

  AccessTemporalSemantic _temporalSemanticForColumn(
    AnalysisColumn column, {
    Iterable<Map<String, dynamic>>? rows,
  }) {
    final explicit = inferExplicitAccessTemporalSemantic(column);
    if (explicit != null && explicit != AccessTemporalSemantic.unknown) {
      return explicit;
    }
    final normalizedType = foldToAscii(column.typeName).toLowerCase().trim();
    if (normalizedType == 'date') {
      return AccessTemporalSemantic.dateOnly;
    }
    if (normalizedType == 'time') {
      return AccessTemporalSemantic.timeOnly;
    }
    if (normalizedType == 'datetime' && _allObservedTemporalValuesAreDateOnly(column, rows)) {
      return AccessTemporalSemantic.dateOnly;
    }
    return inferAccessTemporalSemantic(column);
  }

  bool _allObservedTemporalValuesAreDateOnly(
    AnalysisColumn column,
    Iterable<Map<String, dynamic>>? rows,
  ) {
    if (rows == null) {
      return false;
    }
    var sawValue = false;
    for (final row in rows) {
      final value = _valueForColumn(row, column.name);
      if (value == null) {
        continue;
      }
      final dateTime = _coerceTemporalValue(value);
      if (dateTime == null) {
        continue;
      }
      sawValue = true;
      final utc = dateTime.toUtc();
      if (utc.hour != 0 ||
          utc.minute != 0 ||
          utc.second != 0 ||
          utc.millisecond != 0 ||
          utc.microsecond != 0) {
        return false;
      }
    }
    return sawValue;
  }

  Object? _valueForColumn(Map<String, dynamic> row, String columnName) {
    for (final entry in row.entries) {
      if (_columnLookupKey(entry.key) == _columnLookupKey(columnName)) {
        return entry.value;
      }
    }
    return null;
  }

  DateTime? _coerceTemporalValue(Object value) {
    if (value is DateTime) {
      return value;
    }
    if (value is String) {
      return DateTime.tryParse(value);
    }
    return null;
  }

  String _formatDateOnly(DateTime value) {
    final year = value.year.toString().padLeft(4, '0');
    final month = value.month.toString().padLeft(2, '0');
    final day = value.day.toString().padLeft(2, '0');
    return '$year-$month-$day';
  }

  String _formatTimeOnly(DateTime value) {
    final hour = value.hour.toString().padLeft(2, '0');
    final minute = value.minute.toString().padLeft(2, '0');
    final second = value.second.toString().padLeft(2, '0');
    return '$hour:$minute:$second';
  }

  _CalculatedExpressionKind _inferArithmeticKind(
    _CalculatedExpressionKind left,
    _CalculatedExpressionKind right,
  ) {
    if (_isDateLikeKind(left)) {
      return left;
    }
    if (_isDateLikeKind(right)) {
      return right;
    }
    if (left == _CalculatedExpressionKind.number ||
        right == _CalculatedExpressionKind.number) {
      return _CalculatedExpressionKind.number;
    }
    return _CalculatedExpressionKind.unknown;
  }

  bool _requiresPgcryptoExtension(AnalysisProject project) {
    for (final table in project.tables) {
      for (final column in table.columns) {
        final semantics = _defaultTranslator.translate(
          column,
          rows: table.sampleRows,
        );
        if (semantics?.requiresPgcryptoExtension == true) {
          return true;
        }
      }
    }
    return false;
  }

  String _indexName(AnalysisTable table, AnalysisIndex index) {
    final raw = index.name.trim();
    if (raw.isNotEmpty) {
      return '${table.name}_$raw';
    }
    final suffix = index.columns.map((column) => column.name).join('_');
    return 'idx_${table.name}_$suffix';
  }

  String _constraintName(AnalysisRelationship relationship) {
    final raw = relationship.name.trim();
    if (raw.isNotEmpty) {
      return raw;
    }
    return 'fk_${relationship.fromTable}_${relationship.toTable}';
  }

  String _quotedDbObjectName(String rawName) {
    return identifierPolicy.quotedObjectName(rawName);
  }

  String _sequenceName(AnalysisTable table, AnalysisColumn column) {
    return '${table.name}_${column.name}_seq';
  }

  String _regclassReference(String rawName) {
    return '${_singleQuotedLiteral(identifierPolicy.quotedObjectName(rawName))}::regclass';
  }

  String _singleQuotedLiteral(String value) {
    final escaped = value.replaceAll("'", "''");
    return "'$escaped'";
  }

  String _bytesToHex(Uint8List bytes) {
    final buffer = StringBuffer();
    for (final value in bytes) {
      buffer.write(value.toRadixString(16).padLeft(2, '0'));
    }
    return buffer.toString();
  }
}

class _TranslatedCalculatedExpression {
  final String sql;
  final _CalculatedExpressionKind kind;

  const _TranslatedCalculatedExpression({
    required this.sql,
    required this.kind,
  });
}

enum _CalculatedExpressionKind {
  unknown,
  number,
  text,
  booleanValue,
  datetime,
  dateValue,
  timeValue,
}
