import 'ast/vba_ast.dart';

/// Transpila a AST do VBA gerada pelo `VbaParser` em código Dart válido (AngularDart controllers / Services).
class VbaCompiler {
  final VbaModule _module;
  final StringBuffer _sb = StringBuffer();
  int _indent = 0;

  VbaCompiler(this._module);

  String compile() {
    _sb.writeln('// Auto-generated by VbaCompiler from VBA Source');
    _sb.writeln('class FormBusinessLogic {');
    _indent++;

    for (final sub in _module.subs) {
      _compileSub(sub);
      _sb.writeln();
    }

    _indent--;
    _sb.writeln('}');
    return _sb.toString();
  }

  void _compileSub(VbaSubDeclaration sub) {
    String returnTypeDart = 'void';
    if (sub.isFunction) {
       returnTypeDart = _mapVbaTypeToDart(sub.returnType ?? 'Variant');
    }
    
    _writeIndent();
    _sb.writeln('$returnTypeDart ${sub.name}() {');
    _indent++;
    
    for (final stmt in sub.body) {
      _compileStatement(stmt);
    }
    
    _indent--;
    _writeIndent();
    _sb.writeln('}');
  }

  void _compileStatement(VbaStatement stmt) {
    if (stmt is VbaDimStatement) {
      _writeIndent();
      _sb.writeln('${_mapVbaTypeToDart(stmt.typeName)} ${stmt.variableName};');
    } else if (stmt is VbaAssignment) {
      _writeIndent();
      _sb.write('${stmt.variableName} = ');
      _compileExpression(stmt.value);
      _sb.writeln(';');
    } else if (stmt is VbaCallStatement) {
      _writeIndent();
      _sb.write('${stmt.subName}(');
      for (int i = 0; i < stmt.arguments.length; i++) {
         _compileExpression(stmt.arguments[i]);
         if (i < stmt.arguments.length - 1) _sb.write(', ');
      }
      _sb.writeln(');');
    } else if (stmt is VbaIfStatement) {
      _writeIndent();
      _sb.write('if (');
      _compileExpression(stmt.condition);
      _sb.writeln(') {');
      _indent++;
      for (final s in stmt.thenBranch) {
        _compileStatement(s);
      }
      _indent--;
      
      if (stmt.elseBranch.isNotEmpty) {
         _writeIndent();
         _sb.writeln('} else {');
         _indent++;
         for (final s in stmt.elseBranch) {
           _compileStatement(s);
         }
         _indent--;
      }
      _writeIndent();
      _sb.writeln('}');
    } else if (stmt is VbaForStatement) {
      _writeIndent();
      _sb.write('for (var ${stmt.loopVariable} = ');
      _compileExpression(stmt.startValue);
      _sb.write('; ${stmt.loopVariable} <= '); // Simplificação (assumindo Loop pra cima)
      _compileExpression(stmt.endValue);
      _sb.write('; ${stmt.loopVariable} += ');
      if (stmt.stepValue != null) {
        _compileExpression(stmt.stepValue!);
      } else {
        _sb.write('1');
      }
      _sb.writeln(') {');
      _indent++;
      for (final s in stmt.body) {
        _compileStatement(s);
      }
      _indent--;
      _writeIndent();
      _sb.writeln('}');
    } else if (stmt is VbaDoWhileStatement) {
      _writeIndent();
      _sb.write('while (');
      _compileExpression(stmt.condition);
      _sb.writeln(') {');
      _indent++;
      for (final s in stmt.body) {
        _compileStatement(s);
      }
      _indent--;
      _writeIndent();
      _sb.writeln('}');
    } else if (stmt is VbaOnErrorStatement) {
      _writeIndent();
      if (stmt.target == 'Resume Next') {
        _sb.writeln('// TODO: Implement Try-Catch envelope for On Error Resume Next');
      } else {
        _sb.writeln('// TODO: Implement Try-Catch mapped to label ${stmt.target}');
      }
    }
  }

  void _compileExpression(VbaExpression expr) {
    if (expr is VbaLiteral) {
      if (expr.value is String) {
         _sb.write("'${expr.value}'");
      } else {
         _sb.write(expr.value);
      }
    } else if (expr is VbaIdentifier) {
      _sb.write(expr.name);
    } else if (expr is VbaBinaryOp) {
      _compileExpression(expr.left);
      
      // Mapeia operadores VBA -> Dart
      String mappedOp = expr.operatorStr;
      if (mappedOp == '&') mappedOp = '+'; // concatenação
      if (mappedOp == '=') mappedOp = '=='; // igualdade
      if (mappedOp == '<>') mappedOp = '!='; 
      
      _sb.write(' $mappedOp ');
      _compileExpression(expr.right);
    } else if (expr is VbaCallExpression) {
      _sb.write('${expr.callee}(');
      for (int i = 0; i < expr.arguments.length; i++) {
         _compileExpression(expr.arguments[i]);
         if (i < expr.arguments.length - 1) _sb.write(', ');
      }
      _sb.write(')');
    }
  }

  String _mapVbaTypeToDart(String vbaType) {
    final t = vbaType.toLowerCase();
    switch(t) {
      case 'string': return 'String';
      case 'integer':
      case 'long': return 'int';
      case 'double':
      case 'currency': return 'double';
      case 'boolean': return 'bool';
      case 'variant': return 'dynamic';
      default: return 'dynamic';
    }
  }

  void _writeIndent() {
    _sb.write('  ' * _indent);
  }
}
