Version =20
VersionRequired =20
Begin Report
    AllowDesignChanges = NotDefault
    DateGrouping =1
    GrpKeepTogether =1
    Cycle =1
    PictureType =2
    GridX =24
    GridY =24
    Width =11160
    Tag ="ReportControlDefaults"
    RecSrcDt = Begin
        0xf8f6864ba081e640
    End
    RecordSource ="Contatos"
    Caption ="Contact Phone Book"
    FilterOnLoad =0
    ShowPageMargins =0
    FitToPage =255
    Begin
        Begin Label
            BackStyle =0
            BorderWidth =11
            TextAlign =1
            FontSize =11
            FontName ="Calibri"
            LeftPadding =0
            TopPadding =0
            RightPadding =0
            BottomPadding =0
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            ForeThemeColorIndex =0
            ForeTint =60.0
        End
        Begin CheckBox
            OldBorderStyle =0
            BorderWidth =1
            BorderLineStyle =0
            LabelX =230
            LabelY =-30
            LeftPadding =0
            TopPadding =0
            RightPadding =0
            BottomPadding =0
            BorderThemeColorIndex =3
            BorderShade =90.0
        End
        Begin BoundObjectFrame
            AddColon = NotDefault
            SizeMode =3
            OldBorderStyle =0
            BorderLineStyle =0
            Width =4536
            Height =2835
            LabelX =-1701
            LeftPadding =0
            TopPadding =0
            RightPadding =0
            BottomPadding =0
            BackThemeColorIndex =1
            BorderThemeColorIndex =3
            BorderShade =90.0
        End
        Begin TextBox
            CanGrow = NotDefault
            AddColon = NotDefault
            FELineBreak = NotDefault
            OldBorderStyle =0
            BorderWidth =11
            BorderLineStyle =0
            Width =1701
            LabelX =-1701
            FontSize =11
            FontName ="Calibri"
            AsianLineBreak =1
            LeftPadding =0
            TopPadding =0
            RightPadding =0
            BottomPadding =0
            ShowDatePicker =0
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
        End
        Begin BreakLevel
            GroupHeader = NotDefault
            ControlSource ="=Left([Sobrenome],1)"
        End
        Begin BreakLevel
            ControlSource ="Sobrenome"
        End
        Begin BreakLevel
            ControlSource ="Nome"
        End
        Begin FormHeader
            CanGrow = NotDefault
            Height =0
            Name ="ReportHeader"
            AutoHeight =255
            BackThemeColorIndex =1
        End
        Begin PageHeader
            Height =1770
            Name ="PageHeaderSection"
            AutoHeight =255
            BackThemeColorIndex =1
            Begin
                Begin EmptyCell
                    Width =360
                    Height =360
                    Name ="zecEmptyCell420"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedWidth =360
                    LayoutCachedHeight =360
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin EmptyCell
                    BackStyle =1
                    Left =360
                    Width =9720
                    Height =360
                    Name ="zecEmptyCell421"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedLeft =360
                    LayoutCachedWidth =10080
                    LayoutCachedHeight =360
                    ColumnStart =1
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Top =360
                    Width =360
                    Height =525
                    Name ="zecEmptyCell70"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedTop =360
                    LayoutCachedWidth =360
                    LayoutCachedHeight =885
                    RowStart =1
                    RowEnd =1
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    BorderWidth =0
                    TextAlign =3
                    Left =5760
                    Top =360
                    Width =4320
                    Height =525
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    Name ="txtDate"
                    ControlSource ="=Date()"
                    Format ="Long Date"
                    Tag ="reportdate"
                    GroupTable =1

                    LayoutCachedLeft =5760
                    LayoutCachedTop =360
                    LayoutCachedWidth =10080
                    LayoutCachedHeight =885
                    RowStart =1
                    RowEnd =1
                    ColumnStart =4
                    ColumnEnd =6
                    LayoutGroup =1
                    BorderThemeColorIndex =3
                    BorderShade =90.0
                    ForeThemeColorIndex =2
                    ForeTint =100.0
                    ForeShade =50.0
                    GridlineThemeColorIndex =1
                    GroupTable =1
                    Begin
                        Begin Label
                            BackStyle =1
                            BorderWidth =0
                            Left =360
                            Top =360
                            Width =5400
                            Height =525
                            FontSize =18
                            Name ="lblDate"
                            Caption =" Catálogo Telefônico de Contatos"
                            Tag ="detailformtitle"
                            GroupTable =1
                            LayoutCachedLeft =360
                            LayoutCachedTop =360
                            LayoutCachedWidth =5760
                            LayoutCachedHeight =885
                            RowStart =1
                            RowEnd =1
                            ColumnStart =1
                            ColumnEnd =3
                            LayoutGroup =1
                            ThemeFontIndex =-1
                            ForeThemeColorIndex =2
                            ForeTint =100.0
                            ForeShade =75.0
                            GridlineThemeColorIndex =1
                            GroupTable =1
                        End
                    End
                End
                Begin EmptyCell
                    Top =885
                    Width =360
                    Height =315
                    Name ="zecEmptyCell498"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedTop =885
                    LayoutCachedWidth =360
                    LayoutCachedHeight =1200
                    RowStart =2
                    RowEnd =2
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin EmptyCell
                    BackStyle =1
                    Left =360
                    Top =885
                    Width =360
                    Height =315
                    Name ="zecEmptyCell499"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedLeft =360
                    LayoutCachedTop =885
                    LayoutCachedWidth =720
                    LayoutCachedHeight =1200
                    RowStart =2
                    RowEnd =2
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    BackStyle =1
                    Left =720
                    Top =885
                    Width =2880
                    Height =315
                    Name ="zecEmptyCell500"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedLeft =720
                    LayoutCachedTop =885
                    LayoutCachedWidth =3600
                    LayoutCachedHeight =1200
                    RowStart =2
                    RowEnd =2
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    BackStyle =1
                    Left =3600
                    Top =885
                    Width =2160
                    Height =315
                    Name ="zecEmptyCell501"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedLeft =3600
                    LayoutCachedTop =885
                    LayoutCachedWidth =5760
                    LayoutCachedHeight =1200
                    RowStart =2
                    RowEnd =2
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    BackStyle =1
                    Left =5760
                    Top =885
                    Width =2160
                    Height =315
                    Name ="zecEmptyCell502"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedLeft =5760
                    LayoutCachedTop =885
                    LayoutCachedWidth =7920
                    LayoutCachedHeight =1200
                    RowStart =2
                    RowEnd =2
                    ColumnStart =4
                    ColumnEnd =5
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    BackStyle =1
                    Left =7920
                    Top =885
                    Width =2160
                    Height =315
                    Name ="zecEmptyCell504"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedLeft =7920
                    LayoutCachedTop =885
                    LayoutCachedWidth =10080
                    LayoutCachedHeight =1200
                    RowStart =2
                    RowEnd =2
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Top =1200
                    Width =360
                    Height =330
                    Name ="zecEmptyCell74"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedTop =1200
                    LayoutCachedWidth =360
                    LayoutCachedHeight =1530
                    RowStart =3
                    RowEnd =3
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Left =360
                    Top =1200
                    Width =360
                    Height =330
                    Name ="zecEmptyCell24"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineStyleBottom =1
                    LayoutCachedLeft =360
                    LayoutCachedTop =1200
                    LayoutCachedWidth =720
                    LayoutCachedHeight =1530
                    RowStart =3
                    RowEnd =3
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GridlineThemeColorIndex =2
                    GridlineShade =75.0
                    GroupTable =1
                End
                Begin Label
                    BorderWidth =0
                    Left =720
                    Top =1200
                    Width =2880
                    Height =330
                    FontWeight =700
                    Name ="lblContactName"
                    Caption ="Nome do Contato"
                    GroupTable =1
                    GridlineStyleBottom =1
                    LayoutCachedLeft =720
                    LayoutCachedTop =1200
                    LayoutCachedWidth =3600
                    LayoutCachedHeight =1530
                    RowStart =3
                    RowEnd =3
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    BackThemeColorIndex =-1
                    ForeThemeColorIndex =2
                    ForeTint =100.0
                    ForeShade =75.0
                    GridlineThemeColorIndex =2
                    GridlineShade =75.0
                    GroupTable =1
                End
                Begin Label
                    BorderWidth =0
                    Left =3600
                    Top =1200
                    Width =2160
                    Height =330
                    FontWeight =700
                    Name ="lblBusinessPhone"
                    Caption ="Telefone Comercial"
                    GroupTable =1
                    GridlineStyleBottom =1
                    LayoutCachedLeft =3600
                    LayoutCachedTop =1200
                    LayoutCachedWidth =5760
                    LayoutCachedHeight =1530
                    RowStart =3
                    RowEnd =3
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =-1
                    ForeThemeColorIndex =2
                    ForeTint =100.0
                    ForeShade =75.0
                    GridlineThemeColorIndex =2
                    GridlineShade =75.0
                    GroupTable =1
                End
                Begin Label
                    BorderWidth =0
                    Left =5760
                    Top =1200
                    Width =2160
                    Height =330
                    FontWeight =700
                    Name ="lblHomePhone"
                    Caption ="Telefone Residencial"
                    GroupTable =1
                    GridlineStyleBottom =1
                    LayoutCachedLeft =5760
                    LayoutCachedTop =1200
                    LayoutCachedWidth =7920
                    LayoutCachedHeight =1530
                    RowStart =3
                    RowEnd =3
                    ColumnStart =4
                    ColumnEnd =5
                    LayoutGroup =1
                    BackThemeColorIndex =-1
                    ForeThemeColorIndex =2
                    ForeTint =100.0
                    ForeShade =75.0
                    GridlineThemeColorIndex =2
                    GridlineShade =75.0
                    GroupTable =1
                End
                Begin Label
                    BorderWidth =0
                    Left =7920
                    Top =1200
                    Width =2160
                    Height =330
                    FontWeight =700
                    Name ="lblMobilePhone"
                    Caption ="Celular"
                    GroupTable =1
                    GridlineStyleBottom =1
                    LayoutCachedLeft =7920
                    LayoutCachedTop =1200
                    LayoutCachedWidth =10080
                    LayoutCachedHeight =1530
                    RowStart =3
                    RowEnd =3
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =-1
                    ForeThemeColorIndex =2
                    ForeTint =100.0
                    ForeShade =75.0
                    GridlineThemeColorIndex =2
                    GridlineShade =75.0
                    GroupTable =1
                End
                Begin EmptyCell
                    Top =1530
                    Width =360
                    Height =240
                    Name ="zecEmptyCell484"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedTop =1530
                    LayoutCachedWidth =360
                    LayoutCachedHeight =1770
                    RowStart =4
                    RowEnd =4
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Left =360
                    Top =1530
                    Width =360
                    Height =240
                    Name ="zecEmptyCell485"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =1530
                    LayoutCachedWidth =720
                    LayoutCachedHeight =1770
                    RowStart =4
                    RowEnd =4
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GridlineThemeColorIndex =2
                    GridlineShade =75.0
                    GroupTable =1
                End
                Begin EmptyCell
                    BackStyle =1
                    Left =720
                    Top =1530
                    Width =2880
                    Height =240
                    Name ="zecEmptyCell486"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedLeft =720
                    LayoutCachedTop =1530
                    LayoutCachedWidth =3600
                    LayoutCachedHeight =1770
                    RowStart =4
                    RowEnd =4
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    BackStyle =1
                    Left =3600
                    Top =1530
                    Width =2160
                    Height =240
                    Name ="zecEmptyCell487"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedLeft =3600
                    LayoutCachedTop =1530
                    LayoutCachedWidth =5760
                    LayoutCachedHeight =1770
                    RowStart =4
                    RowEnd =4
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    BackStyle =1
                    Left =5760
                    Top =1530
                    Width =2160
                    Height =240
                    Name ="zecEmptyCell488"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedLeft =5760
                    LayoutCachedTop =1530
                    LayoutCachedWidth =7920
                    LayoutCachedHeight =1770
                    RowStart =4
                    RowEnd =4
                    ColumnStart =4
                    ColumnEnd =5
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    BackStyle =1
                    Left =7920
                    Top =1530
                    Width =2160
                    Height =240
                    Name ="zecEmptyCell490"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedLeft =7920
                    LayoutCachedTop =1530
                    LayoutCachedWidth =10080
                    LayoutCachedHeight =1770
                    RowStart =4
                    RowEnd =4
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BackThemeColorIndex =1
                    GroupTable =1
                End
            End
        End
        Begin BreakHeader
            KeepTogether = NotDefault
            CanGrow = NotDefault
            Height =360
            Name ="CabeçalhoDoGrupo0"
            BackThemeColorIndex =1
            Begin
                Begin EmptyCell
                    Width =360
                    Height =360
                    Name ="zecEmptyCell75"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedWidth =360
                    LayoutCachedHeight =360
                    RowStart =5
                    RowEnd =5
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    BorderWidth =0
                    TextAlign =1
                    Left =360
                    Width =360
                    Height =360
                    FontWeight =700
                    ForeColor =6710886
                    Name ="txtLetter"
                    ControlSource ="=Left([Sobrenome],1)"
                    Tag ="Letter~FieldName=Sobrenome"
                    GroupTable =1
                    GridlineColor =-2147483609

                    LayoutCachedLeft =360
                    LayoutCachedWidth =720
                    LayoutCachedHeight =360
                    RowStart =5
                    RowEnd =5
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    BackThemeColorIndex =-1
                    BorderThemeColorIndex =3
                    BorderShade =90.0
                    ForeTint =60.0
                    GroupTable =1
                End
                Begin EmptyCell
                    Left =720
                    Width =2880
                    Height =360
                    Name ="zecEmptyCell28"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedLeft =720
                    LayoutCachedWidth =3600
                    LayoutCachedHeight =360
                    RowStart =5
                    RowEnd =5
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Left =3600
                    Width =2160
                    Height =360
                    Name ="zecEmptyCell29"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =3600
                    LayoutCachedWidth =5760
                    LayoutCachedHeight =360
                    RowStart =5
                    RowEnd =5
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Left =5760
                    Width =2160
                    Height =360
                    Name ="zecEmptyCell30"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =5760
                    LayoutCachedWidth =7920
                    LayoutCachedHeight =360
                    RowStart =5
                    RowEnd =5
                    ColumnStart =4
                    ColumnEnd =5
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Left =7920
                    Width =2160
                    Height =360
                    Name ="zecEmptyCell31"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =7920
                    LayoutCachedWidth =10080
                    LayoutCachedHeight =360
                    RowStart =5
                    RowEnd =5
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
            End
        End
        Begin Section
            KeepTogether = NotDefault
            CanGrow = NotDefault
            Height =360
            Name ="Detalhe"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
            Begin
                Begin EmptyCell
                    Width =360
                    Height =360
                    Name ="zecEmptyCell76"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedWidth =360
                    LayoutCachedHeight =360
                    RowStart =6
                    RowEnd =6
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Left =360
                    Width =360
                    Height =360
                    Name ="zecEmptyCell25"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineColor =-2147483609
                    LayoutCachedLeft =360
                    LayoutCachedWidth =720
                    LayoutCachedHeight =360
                    RowStart =6
                    RowEnd =6
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GroupTable =1
                End
                Begin TextBox
                    BorderWidth =0
                    TextAlign =1
                    Left =720
                    Width =2880
                    Height =360
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    ForeColor =0
                    Name ="txtContactName"
                    ControlSource ="NomeDoContato"
                    GroupTable =1

                    LayoutCachedLeft =720
                    LayoutCachedWidth =3600
                    LayoutCachedHeight =360
                    RowStart =6
                    RowEnd =6
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    BorderThemeColorIndex =3
                    BorderShade =90.0
                    ForeTint =100.0
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
                Begin TextBox
                    BorderWidth =0
                    TextAlign =1
                    Left =3600
                    Width =2160
                    Height =360
                    TabIndex =1
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    ForeColor =0
                    Name ="txtBusinessPhone"
                    ControlSource ="TelefoneComercial"
                    GroupTable =1

                    LayoutCachedLeft =3600
                    LayoutCachedWidth =5760
                    LayoutCachedHeight =360
                    RowStart =6
                    RowEnd =6
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    BorderThemeColorIndex =3
                    BorderShade =90.0
                    ForeTint =100.0
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
                Begin TextBox
                    BorderWidth =0
                    TextAlign =1
                    Left =5760
                    Width =2160
                    Height =360
                    TabIndex =2
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    ForeColor =0
                    Name ="txtHomePhone"
                    ControlSource ="FoneResidencial"
                    GroupTable =1

                    LayoutCachedLeft =5760
                    LayoutCachedWidth =7920
                    LayoutCachedHeight =360
                    RowStart =6
                    RowEnd =6
                    ColumnStart =4
                    ColumnEnd =5
                    LayoutGroup =1
                    BorderThemeColorIndex =3
                    BorderShade =90.0
                    ForeTint =100.0
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
                Begin TextBox
                    BorderWidth =0
                    TextAlign =1
                    Left =7920
                    Width =2160
                    Height =360
                    TabIndex =3
                    LeftMargin =22
                    TopMargin =22
                    RightMargin =22
                    BottomMargin =22
                    ForeColor =0
                    Name ="txtMobilePhone"
                    ControlSource ="Celular"
                    GroupTable =1

                    LayoutCachedLeft =7920
                    LayoutCachedWidth =10080
                    LayoutCachedHeight =360
                    RowStart =6
                    RowEnd =6
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    BorderThemeColorIndex =3
                    BorderShade =90.0
                    ForeTint =100.0
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
            End
        End
        Begin PageFooter
            Height =0
            Name ="PageFooterSection"
            AutoHeight =255
            BackThemeColorIndex =1
        End
        Begin FormFooter
            CanGrow = NotDefault
            Height =330
            Name ="RodapéDoRelatório"
            AutoHeight =255
            BackThemeColorIndex =1

            Begin
                Begin EmptyCell
                    Top =15
                    Width =360
                    Height =315
                    Name ="zecEmptyCell77"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedTop =15
                    LayoutCachedWidth =360
                    LayoutCachedHeight =330
                    RowStart =7
                    RowEnd =7
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Left =360
                    Top =15
                    Width =360
                    Height =315
                    Name ="zecEmptyCell26"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =360
                    LayoutCachedTop =15
                    LayoutCachedWidth =720
                    LayoutCachedHeight =330
                    RowStart =7
                    RowEnd =7
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Left =720
                    Top =15
                    Width =2880
                    Height =315
                    Name ="zecEmptyCell33"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    GridlineStyleTop =1
                    GridlineWidthTop =2
                    LayoutCachedLeft =720
                    LayoutCachedTop =15
                    LayoutCachedWidth =3600
                    LayoutCachedHeight =330
                    RowStart =7
                    RowEnd =7
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Left =3600
                    Top =15
                    Width =2160
                    Height =315
                    Name ="zecEmptyCell13"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =3600
                    LayoutCachedTop =15
                    LayoutCachedWidth =5760
                    LayoutCachedHeight =330
                    RowStart =7
                    RowEnd =7
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Left =5760
                    Top =15
                    Width =555
                    Height =315
                    Name ="zecEmptyCell445"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =5760
                    LayoutCachedTop =15
                    LayoutCachedWidth =6315
                    LayoutCachedHeight =330
                    RowStart =7
                    RowEnd =7
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Left =6315
                    Top =15
                    Width =1605
                    Height =315
                    Name ="zecEmptyCell14"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =6315
                    LayoutCachedTop =15
                    LayoutCachedWidth =7920
                    LayoutCachedHeight =330
                    RowStart =7
                    RowEnd =7
                    ColumnStart =5
                    ColumnEnd =5
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
                Begin EmptyCell
                    Left =7920
                    Top =15
                    Width =2160
                    Height =315
                    Name ="zecEmptyCell15"
                    GroupTable =1
                    LeftPadding =0
                    TopPadding =0
                    RightPadding =0
                    BottomPadding =0
                    LayoutCachedLeft =7920
                    LayoutCachedTop =15
                    LayoutCachedWidth =10080
                    LayoutCachedHeight =330
                    RowStart =7
                    RowEnd =7
                    ColumnStart =6
                    ColumnEnd =6
                    LayoutGroup =1
                    GridlineThemeColorIndex =1
                    GroupTable =1
                End
            End
        End
    End
End
